### ISSUE TITLE
文章目录显示不全

### ISSUE THREAD

**Issue by mritd** [mzlogin/mzlogin.github.io#10]
文章目录太多会导致显示不全，如下所示

![_023](https://cloud.githubusercontent.com/assets/13043245/19210691/e20ae02e-8d5c-11e6-88f5-a052fce99c13.jpg)

**Comment by mzlogin** [comment]
收到~确实会有这个问题。我稍后想想办法。多谢！

**Comment by mritd** [comment]
恩 好的 ，感谢

**Comment by mzlogin** [comment]
给超长的目录添加了滚动条，更改见：

@7c38d535703fc49f12b47a74fc2a2cde7eba9255

目前不是很完美，无法在滚动文章内容时自动滚动到隐藏状态的目录，没太想好怎么做，记一个 TODO 稍后实现。

- [ ] 自动滚动 TOC

**Comment by mritd** [comment]
好的 谢谢

**Comment by mzlogin** [comment]
@1c159c76bd2ab2f81b3af888ecfe5eaf99bdbad3

修复了在 Windows 下，页面滚动到目录跟随页面移动时，目录栏滚动条已经隐藏，但目录栏的开始部分内容无法显示的问题。

修复方法为当目录跟随页面移动时，目录块自动滚动到它自身的顶部。

**Comment by mritd** [comment]
感谢 :+1:
