### ISSUE TITLE
发现markdown语法中序列号在文中显示无效

### ISSUE THREAD

**Issue by HwiLu** [mzlogin/mzlogin.github.io#100]
如：
```
1. 一
2. 二
```
再文中会显示：

```
1. 一
1. 二

```

**Comment by mzlogin** [comment]
能贴个发生此现象的源文档地址吗？我看下

**Comment by HwiLu** [comment]
> 能贴个发生此现象的源文档地址吗？我看下

刚去复现了一把，请看https://hwilu.github.io/2019/09/18/RedHat-unrar-the-files/，我看我的md语法应该是对的。

**Comment by mzlogin** [comment]
![image](https://user-images.githubusercontent.com/1646590/65844461-f8b18c00-e368-11e9-89db-e2a4a0048609.png)
被中间的内容打断了，这部分内容加缩进。

![image](https://user-images.githubusercontent.com/1646590/65844520-2f87a200-e369-11e9-8249-cb69623f6108.png)

**Comment by HwiLu** [comment]
> ![image](https://user-images.githubusercontent.com/1646590/65844461-f8b18c00-e368-11e9-89db-e2a4a0048609.png)
> 被中间的内容打断了，这部分内容加缩进。
> 
> ![image](https://user-images.githubusercontent.com/1646590/65844520-2f87a200-e369-11e9-8249-cb69623f6108.png)

不对，没有用，我也研究一下，感谢感谢 :smile:

**Comment by HwiLu** [comment]
> > ![image](https://user-images.githubusercontent.com/1646590/65844461-f8b18c00-e368-11e9-89db-e2a4a0048609.png)
> > 被中间的内容打断了，这部分内容加缩进。
> > ![image](https://user-images.githubusercontent.com/1646590/65844520-2f87a200-e369-11e9-8249-cb69623f6108.png)
> 
> 不对，没有用，我也研究一下，感谢感谢 😄

在md编辑器里是正常显示的，post出去就不行了  😢

**Comment by mzlogin** [comment]
有用的。可以参考下我发布的

https://github.com/mzlogin/mzlogin.github.io/blob/master/_posts/2019-09-14-gitee-and-tapd.md

**Comment by HwiLu** [comment]
我知道为啥了，确实是缩进问题。
