### ISSUE TITLE
我觉得wiki，post实际内容部分在显示器上显得太窄了，可以调宽一点吗？具体如何设置，多谢！

### ISSUE THREAD

**Issue by LfqGithub** [mzlogin/mzlogin.github.io#103]

**Comment by mzlogin** [comment]
目前内容展示部分是占四分之三，你如果想修改，可以这样：
post：将 _layouts/post.html 第 31 行 `three-fourths` 改成 `four-fifths`，第 42 行 `one-fourth` 改成 `one-fifth`，这样即改成了五分之四。依此类推，你也可以尝试六分之五，等等。

同理，wiki 是修改 _layouts/wiki.html 的第 18 和 29 行的对应内容。

**Comment by LfqGithub** [comment]
嗯嗯，太感谢楼主了！

额外问一下，有没有可能将目录换到左边? 

另外，在16：9 4k显示器上，网页两边总是大片的空白，这一issue有无优化的可能?

多谢楼主！

**Comment by mzlogin** [comment]
目录可以换到左边啊，你自己调整布局的左右位置就行。

留大片空白是正常的，这个我不认为是问题。你可以看下大部分以内容为空的网站都不会占满整个屏幕，内容占满屏幕的话一行字会非常长，人看起来会费劲很多，体验并不好……

**Comment by LfqGithub** [comment]
嗯嗯，多谢楼主！太感谢了！
