### ISSUE TITLE
搜索框搜索到内容，无法用键盘方向键直接选择搜索内容，只能用鼠标点击

### ISSUE THREAD

**Issue by LfqGithub** [mzlogin/mzlogin.github.io#104]
亲爱的楼主，可否看下您是否也有这个问题？

我在搜索框中搜索到的内容，无法直接用方向键点击打开，感觉这个issue很影响体验。

有劳楼主！

**Comment by LfqGithub** [comment]
我尝试了楼主的网站 https://mazhuang.org/ ，也有同样的问题

**Comment by mzlogin** [comment]
可以按 tab 切换焦点链接（与常见网页和程序窗口行为相同）。

用方向键切换选择内容的交互常见于下拉框、自动补全等，这里的形式是下面的一块原网页上的区域作为结果列表，用方向键操作可能不一定合适……你要是比较在意这块，可以尝试自己改下哈~

**Comment by LfqGithub** [comment]
哇哇，厉害了！这个比方向键切换更便捷，感谢楼主！
