### ISSUE TITLE
可否考虑下添加 flow chart 功能？

### ISSUE THREAD

**Issue by LfqGithub** [mzlogin/mzlogin.github.io#105]
这一功能应该挺常用，奈何我不会设置，楼主可否考虑添加这一功能？多谢！

**Comment by mzlogin** [comment]
这个功能本来就支持的。

效果见 <https://mazhuang.org/wiki/markdown/>

写带这个功能的文章或者 Wiki，写法参考 <https://github.com/mzlogin/mzlogin.github.io/raw/master/_wiki/markdown.md>

**Comment by LfqGithub** [comment]
哦哦，谢谢！学习到了！
