### ISSUE TITLE
undefined method `map' for false

### ISSUE THREAD

**Issue by Lim-LinYuanbo** [mzlogin/mzlogin.github.io#107]
```
ubuntu@VM-0-2-ubuntu:~/mzlogin.github.io$ rm -rf _site/
ubuntu@VM-0-2-ubuntu:~/mzlogin.github.io$ bundle exec jekyll serve
Configuration file: /home/ubuntu/mzlogin.github.io/_config.yml
            Source: /home/ubuntu/mzlogin.github.io
       Destination: /home/ubuntu/mzlogin.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
       Jekyll Feed: Generating feed for posts
   GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
   GitHub Metadata: Failed to open TCP connection to api.github.com:443 (Connection refused - connect(2) for "api.github.com" port 443)
  Liquid Exception: undefined method `map' for false:FalseClass Did you mean? tap in /_layouts/page.html
jekyll 3.8.5 | Error:  undefined method `map' for false:FalseClass
Did you mean?  tap
```

各位有没有遇到这个错误？似乎等一段时间之后再跑就不会有这个问题了？

另外：这个下面这个警告如何处理？我搜索了很久都没找到问题
```
   GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
   GitHub Metadata: Failed to open TCP connection to api.github.com:443 (Connection refused - connect(2) for "api.github.com" port 443)
```

**Comment by mzlogin** [comment]
第一个问题……费解，代码里没有搜到 map 方法。

第二个问题，可以参考 https://github.com/jekyll/github-metadata/blob/master/docs/authentication.md 看下是否能解决。

**Comment by mzlogin** [comment]
经验证，第二个问题可以用以上链接里的第一个方法解决。

![image](https://user-images.githubusercontent.com/1646590/77924001-bf38e980-72d5-11ea-852a-a6a35e9204a9.png)

可以将 JEKYLL_GITHUB_TOKEN 这个变量放到 .zshrc 文件里去。

这样运行右侧仓库可正常显示：

![image](https://user-images.githubusercontent.com/1646590/77924162-f14a4b80-72d5-11ea-8a3a-6350d1a2ddc2.png)

**Comment by Lim-LinYuanbo** [comment]
我的理解是：
假如你的仓库地址是：`https://github.com/mzlogin/mzlogin.github.io.git`
那么运行指令就是：`JEKYLL_GITHUB_TOKEN=https://github.com/mzlogin/mzlogin.github.io.git [bundle exec] jekyll serve`

请问我这样理解对吗？

**Comment by mzlogin** [comment]
> 我的理解是：
> 假如你的仓库地址是：`https://github.com/mzlogin/mzlogin.github.io.git`
> 那么运行指令就是：`JEKYLL_GITHUB_TOKEN=https://github.com/mzlogin/mzlogin.github.io.git [bundle exec] jekyll serve`
> 
> 请问我这样理解对吗？

不是……可以参考我贴的文档的提示，你要到 https://github.com/settings/tokens/new 创建一个有 public_repository 权限的 token，那就是你要用的 JEKYLL_GITHUB_TOKEN 的值。

**Comment by mzlogin** [comment]
@Lim-LinYuanbo 第一个问题我想我找到解决方法了。

我观察到在本地运行出现第一个问题时都伴随着 `Connection refused - connect(2) for "api.github.com" port 443`，所以我开始怀疑是读取 GitHub Metadata 失败后，尝试遍历出错，于是将 _includes/sidebar-popular-repo.html 和 pages/open-source.md 里原本判空的条件

```
{% if site.github.public_repositories != null %}
```

改成了

```
{% if site.github.public_repositories != null and site.github.public_repositories != false %
```

现在可以了，即使偶尔出现 `Connection refused - connect(2) for "api.github.com" port 443` 也能正常跑起来，只是侧边的 repo 没有数据不展示了。

**Comment by Human0722** [comment]
这个问题是读取 Github 项目时网络问题引起的，我也是遇到这个问题，但如果终端走代理能直接跑起来，不会再报错。
