### ISSUE TITLE
关于 Markdown 中 ` ` 语法高亮问题建议

### ISSUE THREAD

**Issue by jijiucheng** [mzlogin/mzlogin.github.io#108]
当下的模板中 Markdown 中 ` ` 语法，背景高亮不是很明显，建议增加灰色深度。

![1111587551524_ pic](https://user-images.githubusercontent.com/15060707/79972420-83ee9c80-84c8-11ea-85cd-9e149a042e6e.jpg)

同时，建议在每篇文章底部可以增加 “版权声明” 类似的板块，可以声明文章版权，同时也方便其他人转载时的声明，希望这个声明内容可以有 “原文作者、原文链接、发表日期、更新日期” 基础的 “超链接”方式，另外可以额外自定义增加其他的声明内容。

**Comment by mzlogin** [comment]
我昨天加了一下，你看看如何。版权声明的内容和样式可以自己修改，位置先占上了…… :smile:

**Comment by mzlogin** [comment]
Issue 我先关闭啦～如果还有相关问题，欢迎重开或者开新 Issue。
