### ISSUE TITLE
关于右侧repository的显示

### ISSUE THREAD

**Issue by Galaxy-Studio-Code** [mzlogin/mzlogin.github.io#109]
请教一下楼主怎么修改或者配置，能实现隐藏部分右侧repository，只显示一部分repo

**Comment by mzlogin** [comment]
你是想配置显示的 repo 数量，还是说就想显示某些指定的 repo？

数量的话，_config.yml 文件里有个变量 side_bar_repo_limit 是控制数量的，目前是按你的 repo 的 star 数量倒序排列，选前 N 个。

如果是想显示指定 repo 的话，可以修改 _includes/sidebar-popular-repo.html 文件里的逻辑，让它满足你指定的条件才展示。

**Comment by user-msi** [comment]
谢谢大佬

**Comment by Galaxy-Studio-Code** [comment]
请问一下要是不显示两个叫galaxy-studio-code.github.io的和叫blog的仓库这个条件判断对吗
```<h3>My Popular Repositories</h3>
{% if site.github.public_repositories != null %}
{% assign repos = site.github.public_repositories | sort: "stargazers_count" | reverse%}
{% for repo in repos | limit: site.side_bar_repo_limit %}
{% if {{ repo.name }} != 'galaxy-studio-code.github.io' and {{ repo.name }} != 'blog' %}
<a href="{{ repo.html_url }}" target="_blank" class="card text-center">
    <div class="thumbnail">
        <div class="card-image geopattern" data-pattern-id="{{ repo.name }}">
            <div class="card-image-cell">
                <h3 class="card-title">
                    {{ repo.name }}
                </h3>
            </div>
        </div>
        <div class="caption">
            <div class="card-description">
                <p class="card-text">{{ repo.description }}</p>
            </div>
            <div class="card-text">
                <span class="meta-info" title="{{ repo.stargazers_count }} stars">
                    <span class="octicon octicon-star"></span> {{ repo.stargazers_count }}
                </span>
                <span class="meta-info" title="{{ repo.forks_count }} forks">
                    <span class="octicon octicon-git-branch"></span> {{ repo.forks_count }}
                </span>
                <span class="meta-info" title="Last updated：{{ repo.updated_at }}">
                    <span class="octicon octicon-clock"></span>
                    <time datetime="{{ repo.updated_at }}">{{ repo.updated_at | date: '%Y-%m-%d' }}</time>
                </span>
            </div>
        </div>
    </div>
</a>
{% endif %}
{% endfor %}
{% endif %}
```

**Comment by mzlogin** [comment]
> 请问一下要是不显示两个叫galaxy-studio-code.github.io的和叫blog的仓库这个条件判断对吗
> 
> ```
> {% if site.github.public_repositories != null %}
> {% assign repos = site.github.public_repositories | sort: "stargazers_count" | reverse%}
> {% for repo in repos | limit: site.side_bar_repo_limit %}
> {% if {{ repo.name }} != 'galaxy-studio-code.github.io' and {{ repo.name }} != 'blog' %}
> <a href="{{ repo.html_url }}" target="_blank" class="card text-center">
>     <div class="thumbnail">
>         <div class="card-image geopattern" data-pattern-id="{{ repo.name }}">
>             <div class="card-image-cell">
>                 <h3 class="card-title">
>                     {{ repo.name }}
>                 </h3>
>             </div>
>         </div>
>         <div class="caption">
>             <div class="card-description">
>                 <p class="card-text">{{ repo.description }}</p>
>             </div>
>             <div class="card-text">
>                 <span class="meta-info" title="{{ repo.stargazers_count }} stars">
>                     <span class="octicon octicon-star"></span> {{ repo.stargazers_count }}
>                 </span>
>                 <span class="meta-info" title="{{ repo.forks_count }} forks">
>                     <span class="octicon octicon-git-branch"></span> {{ repo.forks_count }}
>                 </span>
>                 <span class="meta-info" title="Last updated：{{ repo.updated_at }}">
>                     <span class="octicon octicon-clock"></span>
>                     <time datetime="{{ repo.updated_at }}">{{ repo.updated_at | date: '%Y-%m-%d' }}</time>
>                 </span>
>             </div>
>         </div>
>     </div>
> </a>
> {% endif %}
> {% endfor %}
> {% endif %}
> ```

对的~你这个写法 OK 的。

**Comment by Galaxy-Studio-Code** [comment]
大佬您好，我这么写似乎不行，保存后github提示构建失败

**Comment by mzlogin** [comment]
> 大佬您好，我这么写似乎不行，保存后github提示构建失败

把 if 条件那一行，改成

```
{% if repo.name != 'galaxy-studio-code.github.io' and repo.name != 'blog' %}
```

（去掉了围绕 repo.name 的双花括号。）

**Comment by Galaxy-Studio-Code** [comment]
谢谢大佬，现在可以了

**Comment by mzlogin** [comment]
> 谢谢大佬，现在可以了
> 总算不用cf workers做博客了

哈哈 客气啦~欢迎入坑 GitHub Pages。
