### ISSUE TITLE
关于github pages首页文章列表简介错误问题

### ISSUE THREAD

**Issue by lbcqc** [mzlogin/mzlogin.github.io#112]
新增了一篇文章，在本地jekyll显示没有问题，但是提交到github pages后，首页的文章列表简介行就打印出了全文。找了一轮没找到原因，对jekell也不太了解，求助。。

github上的错误页面（https://lbcqc.github.io/）
![image](https://user-images.githubusercontent.com/22428344/82134308-292b3500-9829-11ea-969f-c744f02b13f9.png)
本地jekell生成的页面
![image](https://user-images.githubusercontent.com/22428344/82134324-45c76d00-9829-11ea-825a-09aa0955a439.png)

**Comment by mzlogin** [comment]
![image](https://user-images.githubusercontent.com/1646590/82140618-ac1cb180-9862-11ea-91aa-e27b7438c988.png)

我这边本地运行也是这样。

差异可能有两种原因：

1. 你本地安装的 jekyll 版本和 GitHub 远程，及我本地的都不一样——我的是 3.8.5 版本；
2. 你的文件在本地换行是正常的，但 Git 推送远程的时候会自动转成 `\r\n`。

出问题的这篇文章的文件我看了下，是因为换行符的问题，正常就是 `\n`，但只有那个文件的换行符是用的 `\r\n`，你把换行转换一下就好了。比如可以用 dos2unix 命令转换那个文件后，就正常了。

![image](https://user-images.githubusercontent.com/1646590/82140696-3fee7d80-9863-11ea-9fd4-30b855ea860c.png)

**Comment by AccelYu** [comment]
我建议改成这样
![Snipaste_2020-05-17_15-59-39](https://user-images.githubusercontent.com/64239154/82141008-96f55200-9865-11ea-8016-78c5d82eada9.png)

**Comment by mzlogin** [comment]
> 我建议改成这样
> ![Snipaste_2020-05-17_15-59-39](https://user-images.githubusercontent.com/64239154/82141008-96f55200-9865-11ea-8016-78c5d82eada9.png)

这也是个办法，但在每篇文章都要手动插入这个标记吧？我不是很喜欢 :smile: 所以还是用的默认 separator

**Comment by lbcqc** [comment]
> ![image](https://user-images.githubusercontent.com/1646590/82140618-ac1cb180-9862-11ea-91aa-e27b7438c988.png)
> 
> 我这边本地运行也是这样。
> 
> 差异可能有两种原因：
> 
> 1. 你本地安装的 jekyll 版本和 GitHub 远程，及我本地的都不一样——我的是 3.8.5 版本；
> 2. 你的文件在本地换行是正常的，但 Git 推送远程的时候会自动转成 `\r\n`。
> 
> 出问题的这篇文章的文件我看了下，是因为换行符的问题，正常就是 `\n`，但只有那个文件的换行符是用的 `\r\n`，你把换行转换一下就好了。比如可以用 dos2unix 命令转换那个文件后，就正常了。
> 
> ![image](https://user-images.githubusercontent.com/1646590/82140696-3fee7d80-9863-11ea-9fd4-30b855ea860c.png)

谢谢，已经解决问题，确实是换行符导致的，应该是之前关掉git的自动转换\r\n导致新加的文章没有转换成\n
