### ISSUE TITLE
上边栏添加后显示404

### ISSUE THREAD

**Issue by Galaxy-Studio-Code** [mzlogin/mzlogin.github.io#116]
以同样的方法添加上边栏后显示404
![image](https://user-images.githubusercontent.com/64064866/83241246-220f0a00-a1cd-11ea-87a8-f547142202b7.png)
![image](https://user-images.githubusercontent.com/64064866/83241342-42d75f80-a1cd-11ea-913b-ab198949a689.png)
![image](https://user-images.githubusercontent.com/64064866/83241354-4834aa00-a1cd-11ea-9583-fc6954c1ad67.png)

**Comment by mzlogin** [comment]
![image](https://user-images.githubusercontent.com/1646590/83252884-99996500-a1de-11ea-9f4d-03268172cb5e.png)

这是链接，文件里要加这个头。
