### ISSUE TITLE
网站使用的仍是mzlogin.gothub.io的资源

### ISSUE THREAD

**Issue by Galaxy-Studio-Code** [mzlogin/mzlogin.github.io#118]
jsdeliver使用的资源以及网站小图标更改不生效，使用的都是mzlogin的资源，config里已更改
![image](https://user-images.githubusercontent.com/64064866/87492965-5146e100-c67e-11ea-9e40-e5a21489c0bc.png)
![image](https://user-images.githubusercontent.com/64064866/87492995-6754a180-c67e-11ea-885f-f9c7a20be86c.png)
![image](https://user-images.githubusercontent.com/64064866/87493219-e77b0700-c67e-11ea-85b5-8f222d111e6d.png)
![image](https://user-images.githubusercontent.com/64064866/87493361-3c1e8200-c67f-11ea-9bf4-a792a17e5896.png)

**Comment by mzlogin** [comment]
是浏览器缓存问题？我看你的页面上资源已经是引用你自己仓库的了。

**Comment by Galaxy-Studio-Code** [comment]
额，谢谢了，没看到邮件，是page build超时了，现在好了
