### ISSUE TITLE
关于keywords

### ISSUE THREAD

**Issue by SinestroEdmonce** [mzlogin/mzlogin.github.io#119]
感谢博主！我用了博主提供的模板，感觉很棒，用起来很顺手。
不过有一个小问题，我想问一下每篇文章最开头有些属性设置，比如layout，title，categories等等，其中keywords是用来做什么的呢？我在博客网站的博文里没有找到显示keywords的地方，而且使用网站的搜索功能去搜索keywords也无法返回具有指定keywords的文章。所以想请教一下博主keywords的用处。

**Comment by mzlogin** [comment]
目前 keywords 的主要作用是在页面的源码里加上这样的两个 meta：

```html
<meta name="keywords" content="Vim, Markdown, md-image-paste.vim">
<meta name="og:keywords" content="Vim, Markdown, md-image-paste.vim">
```

主要是想对搜索引擎友好，暂时没有展示和搜索方面的作用。

不过经你这么一说提醒了我，在网站的搜索功能那里加上应该可以提升体验，我稍后加一下看。

**Comment by mzlogin** [comment]
我在模板里修改了下，网站的搜索功能可以通过关键词搜索文章了。

**Comment by banklc** [comment]
博主，请问一下：整个页面的主题都没有了，只有html的文字，这个是跟代码里面的你的主题无法加载的问题还是可能是哪里的问题？

**Comment by mzlogin** [comment]
> 博主，请问一下：整个页面的主题都没有了，只有html的文字，这个是跟代码里面的你的主题无法加载的问题还是可能是哪里的问题？

贴个链接我看看。另：不要在现有的 Issue 里问不同的问题，如果搜不到同类的 Issue，新开一个 Issue 来讨论会更好。不然会打扰到与此问题无关的人。
