### ISSUE TITLE
点赞功能

### ISSUE THREAD

**Issue by oushu1yefei1** [mzlogin/mzlogin.github.io#121]
您好，请教下想加入一个点赞功能，如何实现？

**Comment by mzlogin** [comment]
是针对什么的呢？文章的还是评论的？

如果是评论的话，可以看下 https://vssue.js.org/zh/demo/github.html 这种效果，OK 的话将评论模块替换为 vssue 即可。

如果是文章的，我暂时没什么好方案。

**Comment by oushu1yefei1** [comment]
谢谢

**Comment by mzlogin** [comment]
现在模板集成的评论框 giscus，从视觉上来可以看作可以对整体和某一个评论点赞，效果上应该可以满足需求。

效果示例：https://mazhuang.org/about/

这个 Issue 我先关闭啦～如果还有相关问题欢迎 reopen 或开新 Issue。
