### ISSUE TITLE
ping绑定的自定义域名返回github.io

### ISSUE THREAD

**Issue by 347900357** [mzlogin/mzlogin.github.io#122]
大佬,为什么ping你的域名不会返回github.io而我的会........
我的博客:https://notepaper.cn/

**Comment by 347900357** [comment]
奥,解决了 A记录解析就不会显示GitHub.io 这个域名

**Comment by mzlogin** [comment]
是的，我是 mazhuang.org 用 A 记录，www.mazhuang.org CNAME 到 mzlogin.github.io
