### ISSUE TITLE
markdown列表显示问题

### ISSUE THREAD

**Issue by wzx140** [mzlogin/mzlogin.github.io#123]
~有序列表和无序列表似乎不能正确显示，只有缩进并没有序号或者小圆点~
~**问题已解决**~
**在PC端显示有问题**，有序列表和无序列表似乎不能正确显示，只有缩进并没有序号或者小圆点
在手机端显示正常

如下所示
```markdown
### 文档
* [中文文档](http://www.kuqin.com/qtdocument/qstring.html)
* [官方文档](http://doc.qt.io/qt-5/qstring.html)
```

![image](https://user-images.githubusercontent.com/25837418/97777546-01981100-1bac-11eb-97ac-a9383200d2fd.png)

**Comment by mzlogin** [comment]
发个链接我看下～我这边没有遇到过这个问题，怀疑是有样式没加载成功

**Comment by wzx140** [comment]
应该是电脑环境问题，我这边用iPad看桌面版网页也没有问题，感谢博主的回复
