### ISSUE TITLE
显示keyword

### ISSUE THREAD

**Issue by wzx140** [mzlogin/mzlogin.github.io#124]
keyword似乎只能用来检索，可以增加配置，显示keyword，便于文章的分类

**Comment by mzlogin** [comment]
> keyword似乎只能用来检索，可以增加配置，显示keyword，便于文章的分类

categories 里可以添加多个 category，可以达到类似的效果

**Comment by wzx140** [comment]
> > keyword似乎只能用来检索，可以增加配置，显示keyword，便于文章的分类
> 
> categories 里可以添加多个 category，可以达到类似的效果

但是keywords可以实现categories下类似二级目录的功能。博主想考虑加一个tag功能吗，可以显示keyword,可以对keyword进行分类查看，主页的标签云可以换成keyword, categories只作为文章的一级分类。

**Comment by mzlogin** [comment]
> > > keyword似乎只能用来检索，可以增加配置，显示keyword，便于文章的分类
> > 
> > 
> > categories 里可以添加多个 category，可以达到类似的效果
> 
> 但是keywords可以实现categories下类似二级目录的功能。博主想考虑加一个tag功能吗，可以显示keyword,可以对keyword进行分类查看，主页的标签云可以换成keyword, categories只作为文章的一级分类。

嗯～你说的意思我明白了。这个之前也有网友提过，但我一直懒没弄……我稍后抽空弄下。

在网上搜了下，可以参考 <https://soyee.me/2018/03/20/jekyll-tags/> 来做。

**Comment by wzx140** [comment]
😃
