### ISSUE TITLE
跨域问题。检索失效

### ISSUE THREAD

**Issue by jiaolonga** [mzlogin/mzlogin.github.io#125]
（原因：CORS 头缺少 'Access-Control-Allow-Origin'）

是我哪里改错了吗，怎么解决啊...? 搜索框失效了

加完域名后就这样了

**Comment by mzlogin** [comment]
_config.yml 里的 url 改成自定义域名的网址

**Comment by jiaolonga** [comment]
> _config.yml 里的 url 改成自定义域名的网址

解决了，感谢大佬的及时回复。

**Comment by mzlogin** [comment]
> > _config.yml 里的 url 改成自定义域名的网址
> 
> 解决了，感谢大佬的及时回复。

客气啦～
