### ISSUE TITLE
My Popular Repositories

### ISSUE THREAD

**Issue by libazong** [mzlogin/mzlogin.github.io#126]
您好，请问如何将My Popular Repositories这一板块删去啊
谢谢

**Comment by mzlogin** [comment]
可以将 _config.yml 里的 side_bar_repo_limit 改成 0，然后将 _includes/sidebar-popular-repo.html 的第一行用 `<!-- -->` 注释掉。

**Comment by libazong** [comment]
哦哦谢谢
