### ISSUE TITLE
issue: 搜索不生效

### ISSUE THREAD

**Issue by mafulong** [mzlogin/mzlogin.github.io#129]
Hi, 之前用的你的模板基于的一个主题，刚刚切到你修改之后的主题，但发现搜索未生效，可以帮忙看下嘛
search_json生成正常，已关闭cdn加速。
博客：https://mafulong.top/
github repo: https://github.com/mafulong/mafulong.github.io

本地部署的一些日志，供参考，可能无关：
```
[2021-03-06 19:16:48] ERROR Errno::ECONNRESET: Connection reset by peer @ io_fillbuf - fd:18
	/usr/local/lib/ruby/gems/3.0.0/gems/webrick-1.7.0/lib/webrick/httpserver.rb:82:in `eof?'
	/usr/local/lib/ruby/gems/3.0.0/gems/webrick-1.7.0/lib/webrick/httpserver.rb:82:in `run'
	/usr/local/lib/ruby/gems/3.0.0/gems/webrick-1.7.0/lib/webrick/server.rb:310:in `block in start_thread'
```
另外
```
ruby
 -v
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin20]
```

**Comment by mzlogin** [comment]
![image](https://user-images.githubusercontent.com/1646590/110206351-179a4300-7eb8-11eb-87cd-197ed9f272d5.png)

在页面 F12 可以看到错误提示，search_json 文件因为跨域问题加载失败了。

可以将 _config.yml 文件里的 url 修改成 https://mafulong.top 再看看。

**Comment by mafulong** [comment]
感激，已解决！

**Comment by mzlogin** [comment]
好的，客气啦～

**Comment by mafulong** [comment]
I'm so sorry, 它又失效，不是跨域问题。
是get json failed,这种情况咋搞呢，这个json链接手动打开是正常的。。前端菜鸡的我哭了

博客：https://mafulong.top/
github repo: https://github.com/mafulong/mafulong.github.io
json链接: https://cdn.jsdelivr.net/gh/mafulong/mafulong.github.io@built/assets/search_data.json 仿照你的仓库使用giuhub action加cns加速

```
Uncaught Error: SimpleJekyllSearch --- failed to get JSON (https://cdn.jsdelivr.net/gh/mafulong/mafulong.github.io@built/assets/search_data.json)
    at o (simple-jekyll-search.min.js:6)
    at simple-jekyll-search.min.js:6
    at XMLHttpRequest.<anonymous> (simple-jekyll-search.min.js:6)
```

**Comment by mzlogin** [comment]
![image](https://user-images.githubusercontent.com/1646590/110880480-ab856800-8319-11eb-9ab4-e6e7ee21000f.png)

![image](https://user-images.githubusercontent.com/1646590/110880438-9a3c5b80-8319-11eb-8f57-d3b5e41177af.png)

内容不满足 JSON 语法，这里多个 `,` @mafulong

**Comment by mafulong** [comment]
好了！！感谢，我可能不适合做程序员。。。

**Comment by mzlogin** [comment]
> 好了！！感谢，我可能不适合做程序员。。。

哈哈哈哈不至于不至于，你是后端么？不擅长前端调试也正常，我现在也是后端，不过搞得比较杂。

**Comment by mzlogin** [comment]
> 好了！！感谢，我可能不适合做程序员。。。

哈哈哈哈不至于不至于，你是后端么？不擅长前端调试也正常，我现在也是后端，不过搞得比较杂。
