### ISSUE TITLE
关于网页的图标问题

### ISSUE THREAD

**Issue by Chem2080** [mzlogin/mzlogin.github.io#135]
![Screenshot_20210620_214857_com chrome dev](https://user-images.githubusercontent.com/69333371/122676679-a6d22900-d211-11eb-9a7a-05aa127fd685.jpg)
见图片左上角
我在库里已经把favicon.ico替换成自己的文件，但是网页的图标依然是mzlogin的，请问应该怎么办？

**Comment by mzlogin** [comment]
如果替换后部署成功的话，那应该就浏览器缓存，换个设备或者浏览器看下。

**Comment by Chem2080** [comment]
> 如果替换后部署成功的话，那应该就浏览器缓存，换个设备或者浏览器看下。

已经清过n遍浏览器缓存了😂然后换浏览器、设备也没有用
难道是因为cdn缓存？

**Comment by mzlogin** [comment]
需要把 https://github.com/Chem2080/chem2080.github.io/blob/main/_config.yml#L14 的 repository 改成你自己的，现在还是写的我的，会引用我的资源，所以你那边看起来没有变化。另外我看到你把 favicon.ico 文件改名了，需要改回来，或者将引用的地方的名字也对应的改掉。

遇到这类问题可以在页面查看下网页源码，确认下引用的资源。

**Comment by mzlogin** [comment]
![image](https://user-images.githubusercontent.com/1646590/122753231-86af7200-d2c4-11eb-8758-f58a5cde02e2.png)

assets/vendor 文件夹没上传，引用的里面的静态资源都找不到报 404 了。

和 .github/workflow 没啥关系，按目前的代码不会影响。

**Comment by Chem2080** [comment]
> ![image](https://user-images.githubusercontent.com/1646590/122753231-86af7200-d2c4-11eb-8758-f58a5cde02e2.png)
> 
> assets/vendor 文件夹没上传，引用的里面的静态资源都找不到报 404 了。
> 
> 和 .github/workflow 没啥关系，按目前的代码不会影响。

好的，谢谢您了
