### ISSUE TITLE
repo是什么？

### ISSUE THREAD

**Issue by skypnn** [mzlogin/mzlogin.github.io#137]
是填会掉链接吗？

**Comment by mzlogin** [comment]
填你的 GitHub 博客博客源码仓库 `{用户名}/{仓库名}`，比如我的就是 `mzlogin/mzlogin.github.io`。

**Comment by skypnn** [comment]
🙏
我知道了，昨天找了很久这个问题，后来才发现fork过来的仓库没有讨论这个模块，然后我新建了个仓就正常了
