### ISSUE TITLE
如何使搜索框和下方卡片对齐？

### ISSUE THREAD

**Issue by Silocean** [mzlogin/mzlogin.github.io#14]
就像下面图中那样，上方的搜索框太短了，怎么让它跟下面的卡片对齐呢？
![qq 20161019165201](https://cloud.githubusercontent.com/assets/6680721/19511998/74d69386-961c-11e6-882b-17ea64b0a338.png)

**Comment by mzlogin** [comment]
已修复，你将上面这次提交的更改应用到你的代码里就好了。

**Comment by mzlogin** [comment]
补充了一下，修复文章页的搜索框的宽度。

**Comment by Silocean** [comment]
Thanks! :smile:
