### ISSUE TITLE
迁移到gitee上提示404

### ISSUE THREAD

**Issue by loflv** [mzlogin/mzlogin.github.io#141]

**Comment by loflv** [comment]
github很多时候无法链接,所以打算迁移到gitee上. github上可以page显示,在gitee上就提示404.救助

**Comment by mzlogin** [comment]
贴个页面链接我看看呢～

**Comment by loflv** [comment]
感谢回复♪(･ω･)ﾉ
github上地址就可以看到页面:https://loflv.github.io/mzlogin.github.io/
gitee上就不行:http://lowie_loflv_room.gitee.io/mzlogin.github.io
怀疑是不是一些插件在gitee上无法使用导致index.html加载失败显示404了

**Comment by mzlogin** [comment]
因为我并没有使用 gitee 托管页面，所以纯看代码也看不出来。

有几个猜测，你可以逐一尝试下

一、看下你的邮箱，有没有收到 build 失败的提示，如果编译失败，GitHub 是会有邮件和页面上的状态提示的；
一、根据 gitee 文档：https://gitee.com/help/articles/4136#article-header3 提交代码后需要手动触发部署，不会自动触发；
二、自定义域名属于 Gitee Pages Pro 付费服务，这里不使用自定义域名的话，将 cname 相关的配置删掉试试，还有 _config.yml 里的 url、baseurl 等也需要根据文档做修改；

**Comment by loflv** [comment]
我下载代码到本地.执行jekyll serve 会提示异常
 You have already activated i18n 1.8.11, but your Gemfile requires i18n 0.9.5.
当我修改命令为 bundle exec jekyll serve 就可以本地部署了
是不是这个原因在gitee上编译运行时失败了呢?

因为我jekyll new projectA . 
projectA 直接运行 jekyll serve没有问题,
projectA push到gitee上可以page预览.
想问下这个异常是什么原因导致的. 感谢回复帮助.

**Comment by mzlogin** [comment]
我一般本地预览也是使用 bundle exec jekyll serve 的，jekyll serve 也会报错。

我对两个命令的区别了解并不确切，从网上搜大致的意思是 bundle exec 才会使用 Gemfile 中约束和 bundle install 安装的版本。

GitHub Pages 官方说明里也是用的 bundle exec jekyll server，https://docs.github.com/cn/pages/setting-up-a-github-pages-site-with-jekyll/testing-your-github-pages-site-locally-with-jekyll

你猜想的原因有可能。应该是 GitHub 与 Gitee 服务端的 Jekyll 版本或者处理流程有差异。

**Comment by loflv** [comment]
放弃在gitee上显示了.当一个备份吧,免得github抽风无法访问就可以了.
感谢(。ˇε ˇ。）
