### ISSUE TITLE
Google Ads

### ISSUE THREAD

**Issue by mafulong** [mzlogin/mzlogin.github.io#142]
老哥了解google ads嘛
尝试申请，反馈说： 在不包含发布商内容的屏幕上展示 Google 投放的广告
和什么设置有关嘛
![image](https://user-images.githubusercontent.com/24795000/147430621-eb77c5a1-033a-4620-8c4c-31c2403de979.png)

另外，这个页面有啥办法可优化嘛，现在我900个博客，它最下面展示了90个button用于跳转，

**Comment by mzlogin** [comment]
可以尝试把分页的每页数量调大点看看。对 Google Ads 我没啥太多了解，比较早申请的一个账号，然后也只在博客上启用了，遇到过的问题比较少。

**Comment by mzlogin** [comment]
最近我优化了一下分页，有需要可以参考下。

**Comment by mafulong** [comment]
@mzlogin 好的好的。
我copy下你的分页 感谢。

**Comment by mzlogin** [comment]
这个问题先关闭了哈～还有相关问题再继续讨论。
