### ISSUE TITLE
搜索那里的url怎么改？我把整个项目里面的mazhuang.org的域名都替换成为了我自己的域名，还是失败

### ISSUE THREAD

**Issue by sky-chy** [mzlogin/mzlogin.github.io#145]
搜索那里的url怎么改？我把整个项目里面的mazhuang.org的域名都替换成为了我自己的域名，然后GitHub上面的也发布了新版的releases来刷新jsdelivr缓存了，还是失败，搜索跳转的仍旧是mazhuang.org下的网页

**Comment by mzlogin** [comment]
现在已经是用的你自己的 url 了，搜索源文件是 <https://cdn.jsdelivr.net/gh/sky-chy/chyblog@built/assets/search_data.json>

但是有个问题是这个文件里面的内容不对。

现在处理方法有两个，一个是将 _config.yml 文件里的 cdn.jsdelivr.enabled 改为 false，不走 jsdelivr 加速。

另一种是将 GitHub Actions 编译配置好，这样的最终结果是 built 分支是你向 master 分支 push 后，GitHub 自动编译更新的，而现在看起来你的 built 分支是自己 push 的编译前的文件。这个过程可以参考 <https://mazhuang.org/2020/10/07/cdn-for-github-pages-2/#0x02-%E7%AB%99%E5%86%85%E6%90%9C%E7%B4%A2%E5%BC%95%E7%94%A8%E7%9A%84-json-%E8%B5%84%E6%BA%90%E5%8A%A0%E9%80%9F>

**Comment by sky-chy** [comment]
没找到这个在哪呢
![image](https://user-images.githubusercontent.com/41139710/161420739-930ab2e2-b03e-4623-af76-06126778d502.png)

**Comment by sky-chy** [comment]
你看看我的actions，好像是需要先创建分支built

**Comment by sky-chy** [comment]
我搞定了，谢谢
