### ISSUE TITLE
只是在_posts中加一个md文件就报错，求助

### ISSUE THREAD

**Issue by novakho** [mzlogin/mzlogin.github.io#147]
只是fork过来上传个文件测试下就报错，求大佬讲讲什么原因
![image](https://user-images.githubusercontent.com/82554084/165698257-20df0937-33ac-4182-9fc2-68d363076f5b.png)

**Comment by mzlogin** [comment]
.github/workflows/ci.yml 里有一个自定义的 action，我看只有这个是失败的。

理论上这个不影响页面发布的，只是用于搜索框加速，但是不知为何你的页面并没有更新。

现在有两种方式可以试下，一是删除这个文件，二是参考 https://mazhuang.org/2020/10/07/cdn-for-github-pages-2/#0x02-%E7%AB%99%E5%86%85%E6%90%9C%E7%B4%A2%E5%BC%95%E7%94%A8%E7%9A%84-json-%E8%B5%84%E6%BA%90%E5%8A%A0%E9%80%9F 将这个 action 配置好。

**Comment by mzlogin** [comment]
Issue我先关闭了哈～有问题可以继续提问。
