### ISSUE TITLE
文章目录过长时无法上下滚动

### ISSUE THREAD

**Issue by Silocean** [mzlogin/mzlogin.github.io#15]
![qq 20161020110638](https://cloud.githubusercontent.com/assets/6680721/19544993/6102a41e-96b5-11e6-9817-27000012ed0f.png)

**Comment by mzlogin** [comment]
See #10 

这个问题已经修复了，在 #10 的评论里有两次 commit 链接，你可以将相应的更改应用到你的代码里。

**Comment by Silocean** [comment]
嗯嗯，感谢！

**Comment by mzlogin** [comment]
不客气哈~ :smile:
