### ISSUE TITLE
你好，我想问下现在githubpage是不是连接不太正常了，现在页面的显示不太正常

### ISSUE THREAD

**Issue by LeventureQys** [mzlogin/mzlogin.github.io#151]
页面是leventureqys.github.io

是什么问题呢？我问了下我朋友，他说是最近免费的cdn被墙了，有什么解决办法吗？

买别的服务商的cdn可以吗？买了之后怎么用呢

求大哥解答一下，拜托了🙏

**Comment by mzlogin** [comment]
是的，就是 jsdelivr 访问不了了。

目前模板没有集成其它免费 cdn，只有是否启用 jsdelivr 的开关。

如果有其它好用的免费 cdn，可以说一下，我看看是否方便集成。

**Comment by LeventureQys** [comment]
> 

免费的不清楚诶，实在不行自己租一个可以吗😥
能否提供个接口让我自己更换呢看🤔我也不太懂，刚入行，第一次用这个

**Comment by mzlogin** [comment]
自己租的话，就自己按选择的 cdn 的文档操作集成就行了哈～按需自行修改源码吧～

**Comment by LeventureQys** [comment]
> 自己租的话，就自己按选择的 cdn 的文档操作集成就行了哈～按需自行修改源码吧～

 好的，我下班了研究一下

**Comment by mzlogin** [comment]
好～Issue我先关了哈～
