### ISSUE TITLE
fatal: 'github-pages-deploy-action-temp-deployment-folder' is not a working tree

### ISSUE THREAD

**Issue by bsauce** [mzlogin/mzlogin.github.io#152]
Run JamesIves/github-pages-deploy-action@3.[6](https://github.com/bsauce/bsauce.github.io/runs/6647690664?check_suite_focus=true#step:5:7).2

    GitHub Pages Deploy Action 🚀

    🚀 Getting Started Guide: https://github.com/marketplace/actions/deploy-to-github-pages
    ❓ FAQ/Wiki: https://github.com/JamesIves/github-pages-deploy-action/wiki
    🔧 Support: https://github.com/JamesIves/github-pages-deploy-action/issues
    ⭐ Contribute: https://github.com/JamesIves/github-pages-deploy-action/blob/dev/CONTRIBUTING.md

    📣 Maintained by James Ives (https://jamesiv.es)
Checking configuration and starting deployment… 🚦
Deploying using …… 🔑
Configuring git…
/usr/bin/git init
Reinitialized existing Git repository in /home/runner/work/bsauce.github.io/bsauce.github.io/.git/
/usr/bin/git config user.name bsauce
/usr/bin/git config user.email fengqiuluo@outlook.com
/usr/bin/git remote rm origin
/usr/bin/git remote add origin ***github.com/bsauce/bsauce.github.io.git
/usr/bin/git fetch --no-recurse-submodules
warning: redirecting to https://github.com/bsauce/bsauce.github.io.git/
From https://github.com/bsauce/bsauce.github.io
 * [new branch]      master     -> origin/master
Git configured… 🔧
Starting to commit changes…
/usr/bin/git ls-remote --heads ***github.com/bsauce/bsauce.github.io.git built | wc -l
warning: redirecting to https://github.com/bsauce/bsauce.github.io.git/
Creating the built branch…
/usr/bin/git checkout --progress --force ddb[7](https://github.com/bsauce/bsauce.github.io/runs/6647690664?check_suite_focus=true#step:5:8)12be5407ef53f2639ab0bb5942ea1ee13723
Note: switching to 'ddb712be5407ef53f2639ab0bb5942ea1ee13723'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at ddb712b Add files via upload
/usr/bin/git checkout --orphan built
Switched to a new branch 'built'
/usr/bin/git reset --hard
/usr/bin/git commit --no-verify --allow-empty -m Initial built commit
[built (root-commit) 9c13[8](https://github.com/bsauce/bsauce.github.io/runs/6647690664?check_suite_focus=true#step:5:9)f3] Initial built commit
/usr/bin/git push --force ***github.com/bsauce/bsauce.github.io.git built
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/bsauce/bsauce.github.io.git/'
Running post deployment cleanup jobs… 🗑️
/usr/bin/git worktree remove github-pages-deploy-action-temp-deployment-folder --force
fatal: 'github-pages-deploy-action-temp-deployment-folder' is not a working tree
Error: The process '/usr/bin/git' failed with exit code [12](https://github.com/bsauce/bsauce.github.io/runs/6647690664?check_suite_focus=true#step:5:13)8
Deployment failed! ❌

**Comment by bsauce** [comment]
![捕获](https://user-images.githubusercontent.com/37901452/170909894-81e2a4f7-7226-4845-8d00-ab236c521e09.PNG)

**Comment by mzlogin** [comment]
我看你删掉了 ci.yml，现在应该没这问题了吧？这种情况应该是 ci.yml 里需要用到的 token 没配置好。

**Comment by bsauce** [comment]
非常感谢，删除后确实不报错了
