### ISSUE TITLE
关于目录显示问题

### ISSUE THREAD

**Issue by bsauce** [mzlogin/mzlogin.github.io#153]
请问一下，我的目录有的显示正常，有的显示不正常，这是怎么回事呢？
![11](https://user-images.githubusercontent.com/37901452/170910844-43084657-3cdb-4662-a614-fd191e4ea496.PNG)
![22](https://user-images.githubusercontent.com/37901452/170910856-96e4927c-a830-435c-a7b1-6777a2fca429.PNG)

**Comment by mzlogin** [comment]
这个不是目录，是文章摘要。

默认是取内容的第一个段落作为摘要，出现你显示里的这种情况一般是对应文件里的换行符和其它的不一样。可以参考 <https://github.com/mzlogin/mzlogin.github.io/issues/47> 处理。

**Comment by bsauce** [comment]
非常感谢，按以下方法解决了。

如果想使用 description，可以将 index.html 文件的第 42 行的 post.excerpt 修改为 post.description。
