### ISSUE TITLE
The deploy step encountered an error: The process '/usr/bin/git' failed with exit code 128

### ISSUE THREAD

**Issue by LeventureQys** [mzlogin/mzlogin.github.io#155]
想问一下这个怎么解决呢，不是很懂这个语言😫
还请UP大大解答
![G(NJYR7RC6J6IHSEAWB`)`O](https://user-images.githubusercontent.com/102945300/181292114-b8adea20-ee7c-4dfe-a1e4-01abfa6a6e5a.png)

**Comment by LeventureQys** [comment]
> 
非常感谢，已经可以了
😭不是很懂git的东西，刚入行，麻烦大大了

**Comment by mzlogin** [comment]
> > 
> 
> 非常感谢，已经可以了 😭不是很懂git的东西，刚入行，麻烦大大了

不客气～
