### ISSUE TITLE
[Feature Request]请求添加一个评论系统:Giscus

### ISSUE THREAD

**Issue by c2xvi** [mzlogin/mzlogin.github.io#159]
官方网站 https://giscus.app/zh-CN
项目仓库 https://github.com/giscus/giscus

推荐原因：因为这个项目是借助Discussions实现评论的，因此不会因为评论产生大量邮件，也不会占用仓库分配的1GB空间。

> 免责声明：本人与该项目完全无关。

**Comment by mzlogin** [comment]
已经加上啦～这个挺好用的，我已经设成默认了，试一段时间看看～
