### ISSUE TITLE
github-pages 未限定版本,导致 jekyll 启动不兼容

### ISSUE THREAD

**Issue by mritd** [mzlogin/mzlogin.github.io#16]
### 问题描述

根目录下 Gemfile 中 没有指定 github-pages 版本限制,导致在物理机安装时执行 `bundle install` 会安装低版本的 github-pages (39),并且其依赖 jekyll 2.4.0,最后会导致 某些依赖错误无法启动

### 解决办法

增加 github-pages 版本限制,比如 `gem 'github-pages', '>= 104'`,这样 `bundle install` 后 jekyll 则会升级到 3.3,依赖也不会出现问题

**Comment by mritd** [comment]
thank you 👍

**Comment by mzlogin** [comment]
确实如此。

这个应该是 bundler 的 bug，在 https://rubygems.org 上 github-pages 的版本是 104，而 bundle install 应该安装已发布的最新稳定版才对，39 都是好老的版本了。

在 bundler 和 pages-gem 项目里有人已经反馈了这个问题。

* <https://github.com/bundler/bundler/issues/5154>
* <https://github.com/github/pages-gem/issues/351>

目前我们临时做这种更改即可，等 bundler 的新版本发布应该就不会这样了。

感谢反馈！ :smile:

**Comment by mritd** [comment]
不太了解 ruby，写了一个 dockerfile，一直放在 docker 里面跑，以前可能一直跑的就是 jekyll2.4 ，这次重新 build 镜像，jekyll 有个库更新了，导致不兼容，研究了半天 发现 jekyll 版本不对 😄

**Comment by mzlogin** [comment]
我是好久没在 Windows 下折腾 Jekyll 了，今天借此机会把 Win10 下的环境又弄起来了，Windows 下弄 Ruby 真是被坑得找不着北……各种奇葩错误。

总之，谢谢你啦！

**Comment by zhangwei900808** [comment]
谢谢正遇到这个问题，哎，jekyll按日期归档搞死人了，楼主有没有什么好方法

**Comment by mritd** [comment]
@zhangwei900808 写个 让客文件 参考我 博客的 https://github.com/mritd/mritd.github.io/blob/master/Rakefile，然后 目录下执行 rake 就行了

**Comment by mzlogin** [comment]
@zhangwei900808 如果你是说类似 <http://template.zhanxin.info/iLotus/archives.html> 这种效果的话，可以基于那个页面的源码 <https://github.com/pizn/iLotus/blob/master/iLotus-jekyll/archives.html> 去实现。
