### ISSUE TITLE
关于文章不显示的问题

### ISSUE THREAD

**Issue by bsauce** [mzlogin/mzlogin.github.io#161]
您好，我目前已经存了很多文章，但是最近两篇文章总是不能展示出来，无法访问，请问是什么原因呢？
是不是文章过多了呢？
项目地址：https://github.com/bsauce/bsauce.github.io
主页：https://bsauce.github.io/
能麻烦您看看吗？
打扰了

**Comment by mzlogin** [comment]
编译出错了。具体的报错信息可以看你的项目地址的提交记录，最近几次都有个红叉，点击进去之后可以看到详情。

比如：https://github.com/bsauce/bsauce.github.io/actions/runs/3442965853/jobs/5744045684

我大致看了下，主要是因为文章里有一些 `{%` / `%}` 和 `{{` / `}}`，这是 Jekyll 所采用的 Liquid 模板语法会最优先解析的，与你的意图不符。

解决方法可以参考：https://github.com/jekyll/jekyll/issues/6217

**Comment by bsauce** [comment]
感谢，以解决
