### ISSUE TITLE
mermaid 渲染问题

### ISSUE THREAD

**Issue by catundercar** [mzlogin/mzlogin.github.io#164]
第一个问题：
**
![image](https://user-images.githubusercontent.com/24569795/224592810-6f05fd5b-2764-481e-9bac-61cec8562275.png)
**

如图，`mermaid`渲染时，第二行没有渲染出来，用的是仓库的mermaid demo.

第二个问题：
![image](https://user-images.githubusercontent.com/24569795/224593337-938fa06a-38f8-4e85-b484-838d35f83011.png)

使用`<div>`标签套`mermaid`启用 mermaid 时与Github渲染mermaid不适配，不知道能否使用` ```mermaid` 启用。

**Comment by mzlogin** [comment]
我看了下 mermaid 的官方文档里的链接，才发现 GitHub 已经原生支持 mermaid 了：https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/

刚刚做了下改造，已经支持 ` ```mermaid ` 的写法了，这样渲染前和渲染后应该都能正常显示图像了。

第一个问题应该是 markdown 的换行问题，经测试在第一行尾加两个空格，或者一二行之间空一行能行。

**Comment by mzlogin** [comment]
博客里的显示效果：

<img width="1090" alt="image" src="https://user-images.githubusercontent.com/1646590/224872960-70a2fedd-0016-44fe-b0ae-ae280aa22809.png">


GitHub 页面显示效果：

<img width="1563" alt="image" src="https://user-images.githubusercontent.com/1646590/224873055-6667a491-282f-4fe5-8000-0c10a4895fb2.png">

**Comment by catundercar** [comment]
感谢！
