### ISSUE TITLE
大佬有没有兴趣加一个相册/图集的功能

### ISSUE THREAD

**Issue by Sawtone** [mzlogin/mzlogin.github.io#176]
在片段或博客里放图集，图片排版格式太过单一，太大影响翻动，太小影响查看，请问是否能够添加相关代码支持，从而可以在片段里实现类似于图集的功能，比如点击放大等等，感谢大佬！

**Comment by mzlogin** [comment]
已更新，添加了一个新的 layout 名叫 gallery，可以实现你说的类似效果。

效果预览：<https://mazhuang.org/2024/04/24/gallery-demo/>

具体实现方法参考我的最新提交。

**Comment by mzlogin** [comment]
![gallery-demo](https://github.com/mzlogin/mzlogin.github.io/assets/1646590/21afd989-7331-4f7b-a8af-2a53d4d9d6aa)

**Comment by Sawtone** [comment]
> l

感谢大佬！这下美美用上了，非常感谢！

**Comment by Sawtone** [comment]
> 已更新，添加了一个新的 layout 名叫 gallery，可以实现你说的类似效果。
> 
> 效果预览：https://mazhuang.org/2024/04/24/gallery-demo/
> 
> 具体实现方法参考我的最新提交 [46ff6e9](https://github.com/mzlogin/mzlogin.github.io/commit/46ff6e96ead6230a5fffbdee610b3dfae9bfbfcf)

感谢大佬！这下美美用上了，非常感谢！

**Comment by Sawtone** [comment]
> 已更新，添加了一个新的 layout 名叫 gallery，可以实现你说的类似效果。
> 
> 效果预览：https://mazhuang.org/2024/04/24/gallery-demo/
> 
> 具体实现方法参考我的最新提交 [46ff6e9](https://github.com/mzlogin/mzlogin.github.io/commit/46ff6e96ead6230a5fffbdee610b3dfae9bfbfcf)

我的博客：https://sawtone.github.io，大佬感兴趣可以看看，目前还很稚嫩，期待以后能把佬的模板发扬光大，哈哈

**Comment by Sawtone** [comment]
一次加载太多图片还是有些卡顿的，不过应该小问题 :D

**Comment by mzlogin** [comment]
> 一次加载太多图片还是有些卡顿的，不过应该小问题 :D

嗯～从我自己的页面看，我感觉主要是因为网络原因，加载静态资源有点费劲，如果挂代理是比较流畅的。

**Comment by mzlogin** [comment]
这个 Issue 我先关闭了哈～还有相关问题再提了～

**Comment by Sawtone** [comment]
> 这个 Issue 我先关闭了哈～还有相关问题再提了～

嗯嗯好，感谢
