### ISSUE TITLE
通过obsidian引用块语法写的md文件发布后，其中的引用块文件链接错误，无法打开

### ISSUE THREAD

**Issue by yutian81** [mzlogin/mzlogin.github.io#178]
例如，我在**obsidian**中通过`引用块`语法，在 `A文档` 中做了这样一个链接：`[[B文档]]`，
并将两篇文章都发布到网页，那么在md文档以及网页上都会显示一个 `B文档` 的链接。
但是，在网页上点击 `B文档` 会显示链接错误，我看了一下，应该是网络路径逻辑有点问题。
两篇文档都发布后，其实际网络地址应该是这样的：
`https://自定义域名/2024/05/01/A文档` 和 `https://自定义域名/2024/05/01/B文档`，
这样分别打开没有问题。
如果从`A文档`中直接点击`引用块`中的`B文档`，`B文档`的地址会被指向：`https://自定义域名/2024/05/01/A文档/B文档.md`，
这个地址是错的，肯定就打不开。
有什么方法能自动识别**obsidian**的`引用块`语法，让他跳转正确的网络地址指向  `https://自定义域名/2024/05/016/B文档`？
我是小白，确实不会改代码，还请大佬指点一下。

**Comment by yutian81** [comment]
另外，我非常喜欢您的这个博客模板，搭建也很简单，我已经删除了其他的博客模板方案，用这个作为主力了。
提一个小小的建议：首页顶部蓝色色块是否可以替换为一张可图片，并在`_config.yml`文件中提供设置选项。
再次感谢。

**Comment by mzlogin** [comment]
GitHub Pages 是基于 Jekyll，和 Obsidian 选用的 Markdown 解析引擎及版本不是统一的，所以书写语法并不完全一致。

在 GitHub Pages 里如果想要引用另一篇文章的链接，是使用标签 `post_url`，使用方法参考 <http://jekyllcn.com/docs/templates/#%E5%8D%9A%E6%96%87%E9%93%BE%E6%8E%A5post-url>。

关于首页顶部背景，谢谢你的建议，我来做一下改造。

**Comment by mzlogin** [comment]
已经在 _config.yml 文件里提供了首页顶部背景色、背景图片的配置选项，具体修改可以参考以上提交。

**Comment by yutian81** [comment]
> 已经在 _config.yml 文件里提供了首页顶部背景色、背景图片的配置选项，具体修改可以参考以上提交。

非常感谢，已经重新配置了首页顶部banner图

**Comment by mzlogin** [comment]
> > 已经在 _config.yml 文件里提供了首页顶部背景色、背景图片的配置选项，具体修改可以参考以上提交。
> 
> 非常感谢，已经重新配置了首页顶部banner图

赞～看着效果还不错。

那这个 Issue 我先关闭了哈～还有其它问题欢迎继续讨论。
