### ISSUE TITLE
图片存储路径是否能从image换到其他

### ISSUE THREAD

**Issue by Zzhiter** [mzlogin/mzlogin.github.io#179]
您好，有一个问题想请教一下：
之前的模板图片都统一放到了image目录下，但是我的博客（或者全部）的图片想放到_post/static目录下，请问有啥设置办法吗？现在的问题是github仓库里面看md文件是没问题的，但是渲染出来的html页面是有问题的
![image](https://github.com/mzlogin/mzlogin.github.io/assets/61727602/9601f86b-d2c9-40c5-aa90-2404d9c5ebd0)

**Comment by mzlogin** [comment]
Jekyll 编译后，_posts 等名称以 `_` 开头的文件夹将不复存在。所以如果想换到其它文件夹，建议自行创建其它文件夹……但这样，与放在 images 里也没啥本质区别了。

**Comment by mzlogin** [comment]
在本地测试 Jekyll 编译后的效果可以参考 <https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/testing-your-github-pages-site-locally-with-jekyll>

编译过后 _site 目录里的就是最终生成的文件。

**Comment by Zzhiter** [comment]
弄好了，感谢🫡
