### ISSUE TITLE
求助：排布混乱

### ISSUE THREAD

**Issue by AndyWang111** [mzlogin/mzlogin.github.io#180]
![页面混乱问题](https://github.com/user-attachments/assets/48f5e180-8a7b-4ce7-89cc-00cc683d2b4a)

**Comment by AndyWang111** [comment]
求助大佬，我也不知道哪的问题

**Comment by AndyWang111** [comment]
已解决，域名问题

**Comment by mzlogin** [comment]
好的，那这个我就先关闭了哈～
