### ISSUE TITLE
搜索功能不可用

### ISSUE THREAD

**Issue by yutian81** [mzlogin/mzlogin.github.io#182]
![image](https://github.com/user-attachments/assets/dd64d6bd-c8d7-4d19-bde4-94a711c61ab9)
搜索功能已开启，但该功能实际不可用。请问应该如何修改代码？

**Comment by mzlogin** [comment]
<img width="1173" alt="image" src="https://github.com/user-attachments/assets/0e0f6001-da4d-40c6-b826-a2cdb9e629f8">

搜索源数据 404 了。

我看你配置里开了 cdn 加速，这样的话，需要将 ci 修复构建 built 分支，目前你的 ci 是还构建失败的状态。这个解决之后应该就好了。

**Comment by yutian81** [comment]
![image](https://github.com/user-attachments/assets/7813d15e-c551-4ee6-b43f-ab33aff52350)
现在已经启用action构建了 built 分支，但还是不可用，麻烦大佬再帮忙看看，万分感谢

**Comment by yutian81** [comment]
关掉cdn之后搜索功能恢复正常了。非常感谢大佬！你这个项目给我带来很多便利，再次感谢！

**Comment by mzlogin** [comment]
不客气

**Comment by mzlogin** [comment]
那这个 Issue 我先关闭了哈～如果有问题可以再开启新的 Issue 讨论。
