### ISSUE TITLE
源码评论框有问题

### ISSUE THREAD

**Issue by qihouying** [mzlogin/mzlogin.github.io#24]
评论框出错啦(990015): 服务异常,请联系客服人员
评论/查看评论 (Show Comments)

**Comment by mzlogin** [comment]
你好~请问你的多说用户名 qihouying 是你在多说网站上申请过的吗？

**Comment by qihouying** [comment]
在多说网上是用这个用户名登录的

**Comment by mzlogin** [comment]
那在多说网上添加了你的博客这个站点吗？我看你的博客里多说的代码是有的，但是加载时出错了，应该是多说网上没有配置好。

**Comment by qihouying** [comment]
确实是因为多说网上没有配置的原因，配置完成就显示了，非常感谢

**Comment by mzlogin** [comment]
不客气哈
