### ISSUE TITLE
请问怎么更换页面的微信公众号图片呢

### ISSUE THREAD

**Issue by sli1989** [mzlogin/mzlogin.github.io#26]
thx，找了半天不知道怎么修改。

**Comment by mzlogin** [comment]
你可以看一下 _includes/article-footer.html，里面有个图片路径就是公众号二维码

**Comment by sli1989** [comment]
还有个问题请教下，为什么我的md文件生成的文章摘要，有的是第一行，有的是全文呢。

**Comment by sli1989** [comment]
没事了 我自己修改了excerpt_separator: "\n" 谢谢

**Comment by banklc** [comment]
请问新版，没有article-foot文件，要在哪里修改？

**Comment by mzlogin** [comment]
> 请问新版，没有article-foot文件，要在哪里修改？

新版默认不会显示二维码了……我页面上展示的是写在 _includes/sidebar-qrcode.html 里，加了判断条件，默认不展示。
