### ISSUE TITLE
多说关闭后的评论模块

### ISSUE THREAD

**Issue by FSilence** [mzlogin/mzlogin.github.io#27]
看到多说要关闭了，，看了下网易云跟帖和畅言 都要求网站备案。。 
不知道您准备换哪家的评论模块

**Comment by mzlogin** [comment]
云跟帖和畅言感觉都比较适合新闻资讯类网站，个人博客的评论人群不太一样，比较重要的评论者个人网站等都没办法设置，所以我也不想用它俩。我现在用的 Disqus，这个在国内基本是不可用状态，国内可用的几家又没有用着放心又合适的，索性就这样了，其实比较尴尬无奈。

**Comment by FSilence** [comment]
其实比较适合新闻类的也能凑付用 可惜必须要求备案才行 很无奈啊

**Comment by mzlogin** [comment]
话说，我前几天把我做的另一个简单模板改成用网易云跟帖了，那时候还没看到说要备案，是这几天新加的规定吗？

**Comment by FSilence** [comment]
我输入我的域名的时候提示域名未被收录， 我理解是没有备案不是吗。。畅言直接要求输入备案号。。

**Comment by FSilence** [comment]
我又去试了一下 这次通过了！！！ 我也不知道为什么了 和之前输入的信息是一致的。。

**Comment by mzlogin** [comment]
哈哈~我也说不好。云跟贴目前应该还没要求备案。通过了就用着吧~也还可以。

**Comment by FSilence** [comment]
现在和你一样注册了Disqus fork了你的项目， 基本没有怎么改动，准备过几天加上百度统计 哈哈 。

**Comment by mzlogin** [comment]
👏
