### ISSUE TITLE
Search does not work

### ISSUE THREAD

**Issue by CodeZeg** [mzlogin/mzlogin.github.io#3]
比较喜欢你这个blog的风格，但是发现搜索不能用啊。

	ReferenceError: event is not defined
	search.js line.25

**Comment by mzlogin** [comment]
咦……奇怪。

请问你使用的是什么浏览器？我在最新的 Chrome，Safari 和 IE11 下试过都可以正常搜索，只不过使用的 js 库对数据源分词不是很好，得出的结果集一般般。

**Comment by CodeZeg** [comment]
firefox

我试了，貌似就这个浏览器不支持。

**Comment by mzlogin** [comment]
已修复，在 IE11，Chrome 50.0.2661.102 m，Firefox 46.0.1 下测试通过。

![search_support_firefox](https://cloud.githubusercontent.com/assets/1646590/15564820/6503757e-2348-11e6-9854-6fbe7914569d.png)
