### ISSUE TITLE
请问页面字体样式和文章字体样式在哪里修改

### ISSUE THREAD

**Issue by sli1989** [mzlogin/mzlogin.github.io#31]
还有主页上部banner的蓝色背景可以换成图片吗
小白，自己找不到。
麻烦你了，谢谢。

**Comment by mzlogin** [comment]
字体和样式大部分在 assets/css/globals/common.css 里可以修改；

蓝色背景可以换成图片，修改 assets/css/pages/index.css 第三行的 background 为 url(图片地址)

**Comment by sli1989** [comment]
感谢

**Comment by mzlogin** [comment]
不客气哈~
