### ISSUE TITLE
站内搜索能力不够

### ISSUE THREAD

**Issue by sli1989** [mzlogin/mzlogin.github.io#32]
发现只能支持标题前几个字。
怎么更新支持标题内容的部分检索。
谢谢答疑。

**Comment by mzlogin** [comment]
站内搜索能力是比较弱，这个主要是没找到很好地对中文标题进行分词的方法。

对于这些我也不太懂，可能需要你自己探索一下了。

你可以参考下 <https://github.com/olivernn/lunr.js> 与 <https://github.com/codepiano/lunr.js>

**Comment by mzlogin** [comment]
参考 <https://github.com/codepiano/lunr.js/issues/3>，如果需要更好的搜索支持，可能得每次提交前，先生成索引文件，如果验证确实有效，生成索引文件的过程可以考虑使用 travis-ci 来自动完成。

**Comment by sli1989** [comment]
好的，感谢。

**Comment by mzlogin** [comment]
已经使用 <https://github.com/christian-fei/Simple-Jekyll-Search> 增强了站内的页面标题搜索能力，中英文都还行，你可以试试新效果啦~
