### ISSUE TITLE
gitment 初始化失败

### ISSUE THREAD

**Issue by imhuay** [mzlogin/mzlogin.github.io#34]
修改`gitment `相关参数后，初始化失败，不知道是不是`Authorization callback URL`写的不对
好像是缺少一个登陆的步骤？
能不能在`README`中更详细的说下评论模块的相关配置，谢谢！

**Comment by mzlogin** [comment]
你需要将 owner 改为你自己的用户名 imhuay，然后将 client_id 和 client_secret 改为你自己的。

在 _config.yml 与 gitment 设置相关的地方我放了一个链接 <https://imsun.net/posts/gitment-introduction/>，是 gitment 作者写的说明，根据那里面的指引你应该能顺利配置好。

还有问题欢迎继续讨论。

**Comment by imhuay** [comment]
这几个地方我都改了，那个链接我也看了，其中第三步-`你需要访问页面并使用你的 GitHub 账号登录`，我找不到哪里登陆GitHub，一进入页面就是`Error: Comments Not Initialized`

**Comment by mzlogin** [comment]
点击评论框的 “Login”？

**Comment by imhuay** [comment]
没有`Login`按钮

**Comment by mzlogin** [comment]
截个图来看看？我去你的页面能看到 Login 按钮。

￼
![default](https://user-images.githubusercontent.com/1646590/27851569-ee7eb83e-618d-11e7-8702-e14072d53cc4.png)

**Comment by imhuay** [comment]
尴尬，搜狗浏览器的问题，换`Chrome`就好了，打扰了

**Comment by mzlogin** [comment]
哈哈 是 IE 内核的问题吧？用搜狗浏览器切换到高速核应该也是没问题的。

身为前搜狗员工，我也是拼了……（逃
