### ISSUE TITLE
disqus无法加载

### ISSUE THREAD

**Issue by chinakevinguo** [mzlogin/mzlogin.github.io#35]
Hi 大神：
              我按照你的教程修改了_config.yml里面的内容，但是，我的disqus无法加载
我的disqus username如下，能分析下为啥吗？
![image](https://user-images.githubusercontent.com/16433937/27861372-38e51ec0-61b3-11e7-8d94-32f121109dcf.png)

**Comment by chinakevinguo** [comment]
ok，可以加载了，原来你这里是写的shortname，而且，你的判断是加在comment.html里面的吗？还有就是，如何能够取消掉gitment后，显示disqus呢？

**Comment by mzlogin** [comment]
将 _config.yml 里的 comments_provider 值改为 disqus，正确填写 disqus 的 username 即可。

**Comment by chinakevinguo** [comment]
我将_config.yml里的comments_provider改为disqus之后，依然无法显示

**Comment by chinakevinguo** [comment]
只有在comments_provider为gitment的时候，点击show disqus comments才能显示，现在我不想要gitment，但是当我注释掉gitment，并且将comments_provider改为disqus之后，下方就没有评论框了。

**Comment by mzlogin** [comment]
你是在国内还是国外？disqus 在国内不可用，在国内的话是否翻墙了？在页面上查看源码是否能看到 disqus 的相关代码吗？

**Comment by chinakevinguo** [comment]
我是在国内啊，使用代理上网了。

**Comment by chinakevinguo** [comment]
而且，很明显，我在使用gitment的时候，点击show disqus comments，能够加载disqus，并不存在被墙了。我只是在将comments_provider改为disqus了之后，就没有评论框了，下面什么都没有。。。

**Comment by mzlogin** [comment]
我现在打开你的博客能看到 disqus 了，改好了？

**Comment by chinakevinguo** [comment]
恩，已经改好了，谢谢了。
