### ISSUE TITLE
样式文件不对怎么处理

### ISSUE THREAD

**Issue by Orangstudio** [mzlogin/mzlogin.github.io#36]
我在本地搭建好ｂｌｏｇ了，但是上传之后演示文件就不对了，以前用hexo 也有同样的问题，在自己的项目名称后面添加仓库的名称，但是现在添加了还是一样的加载不出样式，有人知道怎么解吗？
![_ _20170724161339](https://user-images.githubusercontent.com/23445884/28514970-81ad95f8-708e-11e7-823b-8b47e2279971.png)
![_ _20170724163842](https://user-images.githubusercontent.com/23445884/28514989-934175dc-708e-11e7-9a11-89223cdb483f.png)

**Comment by mzlogin** [comment]
这是我模板存在的一个引用样式文件的相对路径导致的文件，现在已经修复，你可以参考我最新一次提交，主要就是将 _config.yml 里的 url 设置成你的 blog 的根目录，然后将引用资源的路径前面加上 `{{ site.url }}` 变成绝对路径。
