### ISSUE TITLE
内嵌html显示异常可以解决吗

### ISSUE THREAD

**Issue by SilverBulletZyp** [mzlogin/mzlogin.github.io#38]
我最早用的是huangxuan的模板，由于之前没有大纲功能，就使用了DongChuan的模板，后来看到了你修改的这个版本挺喜欢，想后续使用你的版本。

在DongChuan的模板里有个问题，我写表格需要一些合并单元格等功能，基本的markdown是不支持的，于是写了一段html的table放在文章中，却发现文章直接被当成html解析了，内容显示没问题，头部的layout等标签块无法识别了，显示出了点问题，而且回到主页的目录里，文章标题下的简介也无法正确识别了，直接变成了整个文章内容。

猜想可能是markdown内嵌html代码后自动解析出了问题，没有找到有效的解决办法，请问博主有遇到这个问题或是有好的解决办法吗？

**Comment by mzlogin** [comment]
我倒是还没遇到过，当然也可能是因为我没有尝试过手写表格合并单元格。

可以提供一段能复现问题的代码吗？我可以试试看。

**Comment by SilverBulletZyp** [comment]
使用原先DongChuan的模板，尝试加入表格

比如简单的片段：

```html
<table>
		<tr>
				<th width="60%" colspan="2">命令</th>
				<th width="40%">描述</th>
		</tr>
		<tr>
				<td rowspan="2">init</td>
				<td>git init</td>
				<td>本地初始化git仓库</td>
		</tr>
		<tr>
				<td>git clone xxx</td>
				<td>从远程服务器克隆仓库到本地</td>
		</tr>
</table>
```

展示效果类似这样：

<img width="780" alt="33333333" src="https://user-images.githubusercontent.com/12904640/30274169-d145022e-972e-11e7-914b-9533c7a779eb.png">


文章顶部默认内容为：


```
---
layout: post
title: Git学习汇总
category: Resource
tags: [Resource]
---
> git资源与使用
```


顶部的展示效果和目录的文章副标题都会显示一些异常

**Comment by SilverBulletZyp** [comment]
文章内容都是正常的，主要就是表格的标签自动当成html解析后，顶部的markdown文章标记部分，没有能够正常隐藏掉，同时，外部目录的副标题应该调用第一行的注释，可却变成了文章前几行的内容

**Comment by mzlogin** [comment]
我遇到过 YAML 头后面不加空行出现这种问题，所以我现在都是空一行再开始内容，你试试这个？

**Comment by SilverBulletZyp** [comment]
我试之后还是会有这个问题

<img width="529" alt="777777" src="https://user-images.githubusercontent.com/12904640/30277800-7101a536-973b-11e7-9c83-bdf5ae8e6b60.png">

目录部分：

<img width="396" alt="88888" src="https://user-images.githubusercontent.com/12904640/30277832-82c1f82a-973b-11e7-9297-c70b0faa6464.png">

你那边也会有这种情况吗？

**Comment by mzlogin** [comment]
我在我的博客里加了一篇文章，使用你上面提供的头和 HTML 代码，本地预览没有复现问题。

**Comment by SilverBulletZyp** [comment]
好的，不知道是不是版本问题，回头我用你的模版构建仓库时测试一下，非常感谢了！
