### ISSUE TITLE
clone和frok之后页面错乱布局图片不显示

### ISSUE THREAD

**Issue by chaodongyang** [mzlogin/mzlogin.github.io#39]
1，url: 自定义域名目前不支持 https
2，organization_url: 改为自己的网址
3，github_username：改为自己的 github 用户名
4，repository: 改为自己的仓库

**Comment by chaodongyang** [comment]
问题一解决

**Comment by mzlogin** [comment]
@lyk7539511 可以使用的，上面说的是使用自定义域名的情况，github 域名把 url 和其他配置项弄好就行。

**Comment by lyk7539511** [comment]
@mzlogin好的，谢谢
