### ISSUE TITLE
运行后旁边 My Popular Repositories  没有内容

### ISSUE THREAD

**Issue by ychost** [mzlogin/mzlogin.github.io#4]

**Comment by ychost** [comment]
没有那些卡片。

**Comment by ychost** [comment]
明白了，原来是调用了github 的 repos 谢谢楼主了

**Comment by mzlogin** [comment]
嗯嗯~是使用的 `site.github.public_repositories`，所以本地 Jekyll 预览的时候是看不到的。

我看你的博客已经弄好啦~ :+1: 

我关闭 Issue 了哈！
