### ISSUE TITLE
关于页面跳转问题{{post.url}} 参数

### ISSUE THREAD

**Issue by GoldIsland** [mzlogin/mzlogin.github.io#48]
您好，我使用了您的博客设置，站点在这里 https://goldisland.github.io/gengdu/
我的文章点击的时候，会把gengdu这个丢失掉，不知道是什么原因呢？ 
我看了heads.html 使用的是{{post.url}} 变量，不知道这个变量在哪里设置。

**Comment by mzlogin** [comment]
`post.url` 是 Jekyll 程序维护的一个地址，形如 `/2017/12/23/myblog-birth/` 这种，这个相对地址是基于你的域名根目录的，即 `https://goldisland.github.io/`，所以使用这种地址的地方都会出现你说的这个问题，比如顶部的链接等等。链接会被识别为 `https://goldisland.github.io/2017/12/23/myblog-birth/` 这样。这算是博客模板的一个问题，我晚上改一下，然后再来答复你。

感谢反馈~

**Comment by mzlogin** [comment]
问题应该解决了，见 https://github.com/mzlogin/mzlogin.github.io/commit/3ee62a7a5d14f7ff6ac971edcd331c44fd642cc7

**Comment by GoldIsland** [comment]
首页和分类等navs也存在这个问题，需要在header.html 中 site-header-nav 中添加 site.url 变量。 我已经改过啦

**Comment by mzlogin** [comment]
嗯嗯~确实。在 footer.html 里也有 navs，需要做一样的修改，还有 footer.html 与 header.html 里各有一处使用 `site.subscribe_rss` 的地方也要改。
