### ISSUE TITLE
请问下，推荐，置顶功能可以怎么做

### ISSUE THREAD

**Issue by fengjx** [mzlogin/mzlogin.github.io#49]

**Comment by mzlogin** [comment]
可以在每篇日志的顶部加变量标识是否置顶或推荐，比如

```
---
layout: post
...
ahead: true
recommend: true
---
```

然后在 index.html 里遍历所有日志的时候（index.html 里 36-56 行），用 post.ahead 和 post.recommend 来判断，然后做对应的处理。

**Comment by dzxindex** [comment]
这个功能能更新到代码么？
