### ISSUE TITLE
Feed.xml shows incorrectly

### ISSUE THREAD

**Issue by CaptainJe** [mzlogin/mzlogin.github.io#5]
Click the feed button at the bottom of every page, then you'll see codes, i think this is not what the designer wants to show.

**Comment by mzlogin** [comment]
我大概明白你的意思，你是想用户能更方便地通过点击订阅到他的订阅器里去？那你可以看看国内的鲜果，国外的 feedburner 等服务，然后自己对相关代码稍作修改。

我在页面底部添加 feed button 的目的与此不大一致，只是想让使用 feed 订阅的用户能知道我的 feed url，然后如果他需要，可以手动添加到他的 feed 订阅器里去。虽然现在存活的 feed 订阅服务已经没以前那么多了，但我也没办法找到一个集成所有主流订阅服务的控件或服务去展示在这里，既然如此那我就只提供最通用的方案——url。

**Comment by CaptainJe** [comment]
恩，了解了。
我是做嵌入式开发的，对前端技术不是那么了解，
看到点个 button 出来一堆 xml 语句就以为出 bug 了，囧。

我工作三年，开始整理自己的技术栈，用你这个漂亮的主题搭建了自己的博客，谢谢贡献。
打码改变人生，哈哈，共勉。

**Comment by mzlogin** [comment]
@CaptainJe 共勉，加油~ :+1:
