### ISSUE TITLE
如何添加mathjax支持？

### ISSUE THREAD

**Issue by wonter** [mzlogin/mzlogin.github.io#50]
我把
```html
<script type="text/javascript"  src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script> 
```
添加到了_layouts/post.html上面

然后我写好数学公式后去页面看了一眼源代码，发现是有`<script type="math/tex">\frac{N - 1}{2} \times \frac{L}{R}</script>`的
 
但是显示的是空白

<img width="135" alt="_15143673414547" src="https://user-images.githubusercontent.com/17780091/34377529-671eaed4-eb2c-11e7-9d03-11ef12089109.png">

这是我的_layouts/post.html源码

```html
---
layout: default
---

<script type="text/javascript"  src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script> 


<section class="collection-head small geopattern" data-pattern-id="{{ page.title | truncate: 15, ''}}">
<div class="container">
  <div class="columns">
    <div class="column three-fourths">
      <div class="collection-title">
        <h1 class="collection-header">{{ page.title }}</h1>
        <div class="collection-info">
          {% if page.date %}
          <span class="meta-info">
            <span class="octicon octicon-calendar"></span> {{ page.date | date: "%Y/%m/%d" }}
          </span>
          {% endif %}
...
```

**Comment by mzlogin** [comment]
我试了一下也是如此，我再琢磨琢磨，咱们谁有结果了就在这回复同步一下~ 😄

**Comment by mzlogin** [comment]
我尝试成功了，用法没什么区别啊……

效果见

http://mazhuang.org/wiki/markdown/#mathjax

**Comment by mzlogin** [comment]
![image](https://user-images.githubusercontent.com/1646590/34380432-4cb149de-eb3c-11e7-97da-7321b954437c.png)

在浏览器控制台可以看到你的失败的原因，因为 github.io 域名是 https 的，然后引用的 MathJax.js 文件是 http 的，这样会被认为不安全，block 掉了。

**Comment by mzlogin** [comment]
我能想到的一种解决方案是你 fork 一下 <https://github.com/mathjax/MathJax> 这个仓库，然后在你 fork 的仓库的 Settings 里把 GitHub Pages 的 source 设为 master branch，再把上面引用的这个 MathJax.js 的路径改为 https://wonter.github.io/MathJax/MathJax.js

**Comment by wonter** [comment]
@mzlogin 谢谢，也可以使用官方给的https链接

`<script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML'></script>
`

**Comment by mzlogin** [comment]
@wonter 嗯嗯~我也看到官方给的链接，不过当时想着 cloudflare 的部分服务在国内处于被墙的状态，所以就没有考虑用。如果它的 cdnjs 国内能正常访问，那用这个就最好了。
