### ISSUE TITLE
求解决

### ISSUE THREAD

**Issue by kingrome2017** [mzlogin/mzlogin.github.io#54]
部署到线上就是这样

--- layout: default class: home css: ['pages/index.css'] comments: false ---
{{ site.subtitle }}
{{ site.location }} {{ site.organization }} {{ site.github_username }}
{% for post in paginator.posts %}
{{ post.title }}
{{ post.excerpt | strip_html | strip }}

{{ post.date | date: "%Y/%m/%d" }} {% for cat in post.categories %} {{ cat }} {% endfor %}

{% endfor %}
{% include sidebar-search.html %} {% include sidebar-popular-repo.html %}
{% if paginator.previous_page %} {% if paginator.previous_page == 1 %} « {% else %} « {% endif %} {% else %}  « {% endif %} {% if paginator.page == 1 %} 1 {% else %} 1 {% endif %} {% for count in (2..paginator.total_pages) %} {% if count == paginator.page %} {{count}} {% else %} {{count}} {% endif %} {% endfor %} {% if paginator.next_page %} » {% else %}  » {% endif %}

**Comment by mzlogin** [comment]
你把仓库的名字参考一下 README.md 里讲的，看你是否需要改一下，然后 _config.yml 里的 url 配置成对应的。

**Comment by kingrome2017** [comment]
# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://lisj.netlify.com
date_format: "ordinal"
title: 码志
subtitle: "打码改变人生"
description: "马壮的个人博客"
keywords: 码志, Zhuang Ma, mzlogin, mazhuang
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Zhuang Ma
organization: zkh360.com
organization_url: http://www.zkh360.com
github_username: mzlogin
location: Wuhan, China
email: chumpma@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: kingrome2017/lishijie.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours

# https://github.com/gitalk/gitalk#install
gitalk:
    owner: kingrome2017
    repo: lishijie.github.io
    clientID: 78d8bc455509831a058f
    clientSecret: f14d1d85e2542f124725dfbe3ad5b90b9640c269
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1

**Comment by kingrome2017** [comment]
上面是我修改的还是不行

**Comment by mzlogin** [comment]
你项目地址是什么？

**Comment by kingrome2017** [comment]
github.com/kingrome2017/lishijie.github.io

**Comment by kingrome2017** [comment]
上面是我的项目地址

**Comment by mzlogin** [comment]
看不懂你的配置，你 CNAME 填的 `lisj.netlify.io` 无法访问。

我建议的步骤：

1. 将项目名称改为 kingrome2017.github.io
2. 将 CNAME 文件删掉
3. 将 url 改为 https://kingrome2017.github.io

这样你应该能正常访问了，然后你再弄 CNAME 的事。

**Comment by mzlogin** [comment]
我看到你的博客已经配置好了，我关闭 Issue 啦~
