### ISSUE TITLE
关于搜索框的改进

### ISSUE THREAD

**Issue by colingpt** [mzlogin/mzlogin.github.io#55]
主题非常漂亮，特别是边栏的搜索框的下拉列表显示方式，感谢分享！

但似乎这个搜索只能搜索标题不能搜索全文，以前用[jekyll-jacman](https://github.com/Simpleyyt/jekyll-jacman)主题，使用了[Simple-Jekyll-Search](https://github.com/christian-fei/Simple-Jekyll-Search)功能，尽管不能像您这个下拉显示，但可以全文搜索，非常方便。

可否借鉴改进？或者在右上角再添加一个搜索框实现全文搜索？

期待！

**Comment by mzlogin** [comment]
@colingpt 感谢你的建议，我这个搜索实际上也是使用的 Simple-Jekyll-Search，只是因为搜索数据源是在同一个文件里，因为我觉得全文数据加入会导致这个文件过大，所以没有加入全文数据。

你要实现这个也非常容易，修改 assets/search_data.json 文件，在第 17 行后面添加

```
"content"  : "{{ doc.content | strip_html | strip_newlines }}"
```

即可。（注意第 16 行最后要加逗号）

参考 <https://github.com/christian-fei/Simple-Jekyll-Search/wiki>

**Comment by mzlogin** [comment]
我在 _config.yml 文件里新增了 simple_jekyll_search 相关的配置，可以开关全文搜索和设置搜索结果条数据，你可以参考修改啦。

参考

https://github.com/mzlogin/mzlogin.github.io/blob/master/_config.yml#L111

https://github.com/mzlogin/mzlogin.github.io/blob/a419c2d457a240367b3b5926d8dba700c4445778/_includes/sidebar-search.html#L20

https://github.com/mzlogin/mzlogin.github.io/blob/a419c2d457a240367b3b5926d8dba700c4445778/assets/search_data.json#L18

另外注意我替换了 Simple-Jekyll-Search 的 js 文件为最新版本。
