### ISSUE TITLE
chrome打开显示问题

### ISSUE THREAD

**Issue by buaawht** [mzlogin/mzlogin.github.io#58]
你好，我按照您的步骤搭建了一下，什么东西我都不改动，直接fork后，结果chrome打开我的io地址后一直显示界面如下：
![shot](https://user-images.githubusercontent.com/19142533/37254435-c82e0586-2578-11e8-9ef6-a52115a47dad.jpg)，
请问这情况是怎么回事？

**Comment by mzlogin** [comment]
![image](https://user-images.githubusercontent.com/1646590/37261642-1d5ee498-25d9-11e8-9759-6ce83f564ed2.png)
在 Chrome console 能看到错误提示，你把 _config.yml 里的 url 改成 https 的试试？
