### ISSUE TITLE
GitPage配置自定义域名后提示证书错误

### ISSUE THREAD

**Issue by Huang-Libo** [mzlogin/mzlogin.github.io#6]
我配置好git page的自定义顶级域名后，在chrome上可以打开，但是在Safari上打开就提示证书错误，是因为Safari自动跳转到了https上去了（这是为什么？），另外，chrome上打开www二级域名就提示隐私错误，这又是为什么？
我试了试你的域名，顶级域名和www二级域名在chrome上和Safari上都很好使，请问是怎么做到的？

**Comment by mzlogin** [comment]
自定义域名如果没有使用第三方 CDN + 为你的域名申请的证书配合 GitHub Pages 使用的话，不要使用 https 访问，因为默认是使用的 www.github.com 的证书，与你的域名不匹配自然就会报证书错误了。

我目前使用的方案是完全 http，不使用 https，也建议谷歌只收录我博客 http 开头的链接。

我以前也折腾过 https，后来使用的第三方 CDN 服务商停止服务了，我就改回来了。以前折腾的记录供你参考：

* [为绑定域名的 GitHub Pages 启用 HTTPS](http://mazhuang.org/2016/05/21/enable-https-for-github-pages/)
* [Kloudsec 挂了，GitHub Pages 去 HTTPS 化](http://mazhuang.org/2016/07/11/remove-https/)

如果你现在使用 http 会自动跳转到 https 的话，如果你没有故意配置成这样，那应该是浏览器缓存，你清一下缓存看下。

**Comment by Huang-Libo** [comment]
果然是缓存问题...
感谢提醒。

**Comment by mzlogin** [comment]
不客气~
