### ISSUE TITLE
图片不显示了，刚发现怎么回事？

### ISSUE THREAD

**Issue by chaodongyang** [mzlogin/mzlogin.github.io#60]
github显示上传是成功的。在仓库也能看到图片。但是在网站上看不到了。并且之前所有上传的都看不到了

**Comment by LfqGithub** [comment]
这个应该是图片被墙了，翻墙就能看到图片了。

**Comment by youngwanjin** [comment]
我也遇到了相同问题，仓库有显示，但是网站看不到，翻墙也看不到

**Comment by mzlogin** [comment]
> 我也遇到了相同问题，仓库有显示，但是网站看不到，翻墙也看不到

![image](https://user-images.githubusercontent.com/1646590/82329303-b16d2e00-9a13-11ea-98fb-a9dd2639c1bd.png)

控制台有提示，图片地址跨域引用问题。

不要这样写图片地址吧，比如你的博客里的

```
![](https://github.com/youngwanjin/youngwanjin.github.io/blob/master/images/posts/openstack/lbaas-v1.png)
```

你就写相对路径于你博客根目录的路径就行了：

```
![](/images/posts/openstack/lbaas-v1.png)
```

**Comment by LfqGithub** [comment]
我以前插入图片这么做：
<div align="center"><img width="800" src="https://raw.githubusercontent.com/github_name/github_pages_repos/master/dir/figure.png"/></div>

可以方便的调节图片大小、对齐方式。但是换用您介绍的这种方式：![](/images/posts/openstack/lbaas-v1.png)， 就无法调节了，请问有对应的解决方案吗？ 谢谢！

**Comment by mzlogin** [comment]
> 我以前插入图片这么做：
> `<div align="center"><img width="800" src="https://raw.githubusercontent.com/github_name/github_pages_repos/master/dir/figure.png"/></div>`
> 
> 可以方便的调节图片大小、对齐方式。但是换用您介绍的这种方式：`![](/images/posts/openstack/lbaas-v1.png)`， 就无法调节了，请问有对应的解决方案吗？ 谢谢！

有一种方法是使用 Inline Attribute。

```
![](/images/posts/openstack/lbaas-v1.png){:.center-w800}
```

后面这个 `center-w800` 是自己定义的一个 css class，包含居中和宽度 800 样式。

**Comment by LfqGithub** [comment]
> > 我以前插入图片这么做：
> > `<div align="center"><img width="800" src="https://raw.githubusercontent.com/github_name/github_pages_repos/master/dir/figure.png"/></div>`
> > 可以方便的调节图片大小、对齐方式。但是换用您介绍的这种方式：`![](/images/posts/openstack/lbaas-v1.png)`， 就无法调节了，请问有对应的解决方案吗？ 谢谢！
> 
> 有一种方法是使用 Inline Attribute。
> 
> ```
> ![](/images/posts/openstack/lbaas-v1.png){:.center-w800}
> ```
> 
> 后面这个 `center-w800` 是自己定义的一个 css class，包含居中和宽度 800 样式。

抱歉做伸手党，请问这个css应该写在什么地方？可否给个示例代码？谢谢！

**Comment by mzlogin** [comment]
> > > 我以前插入图片这么做：
> > > `<div align="center"><img width="800" src="https://raw.githubusercontent.com/github_name/github_pages_repos/master/dir/figure.png"/></div>`
> > > 可以方便的调节图片大小、对齐方式。但是换用您介绍的这种方式：`![](/images/posts/openstack/lbaas-v1.png)`， 就无法调节了，请问有对应的解决方案吗？ 谢谢！
> > 
> > 
> > 有一种方法是使用 Inline Attribute。
> > ```
> > ![](/images/posts/openstack/lbaas-v1.png){:.center-w800}
> > ```
> > 
> > 
> > 后面这个 `center-w800` 是自己定义的一个 css class，包含居中和宽度 800 样式。
> 
> 抱歉做伸手党，请问这个css应该写在什么地方？可否给个示例代码？谢谢！

可以写在 assets/css/globals/common.css 里。我没有现成的代码，给个写法，具体样式你自己调一调：

```css
.center-w800 {
  width: 800px;
}
```

**Comment by LfqGithub** [comment]
> > > > 我以前插入图片这么做：
> > > > `<div align="center"><img width="800" src="https://raw.githubusercontent.com/github_name/github_pages_repos/master/dir/figure.png"/></div>`
> > > > 可以方便的调节图片大小、对齐方式。但是换用您介绍的这种方式：`![](/images/posts/openstack/lbaas-v1.png)`， 就无法调节了，请问有对应的解决方案吗？ 谢谢！
> > > 
> > > 
> > > 有一种方法是使用 Inline Attribute。
> > > ```
> > > ![](/images/posts/openstack/lbaas-v1.png){:.center-w800}
> > > ```
> > > 
> > > 
> > > 后面这个 `center-w800` 是自己定义的一个 css class，包含居中和宽度 800 样式。
> > 
> > 
> > 抱歉做伸手党，请问这个css应该写在什么地方？可否给个示例代码？谢谢！
> 
> 可以写在 assets/css/globals/common.css 里。我没有现成的代码，给个写法，具体样式你自己调一调：
> 
> ```css
> .center-w800 {
>   width: 800px;
> }
> ```

嗯嗯，运行成功，太感谢了！
