### ISSUE TITLE
发布的新文章提示“未找到相关的 Issues 进行评论，请联系xxx初始化创建”

### ISSUE THREAD

**Issue by xoyabc** [mzlogin/mzlogin.github.io#63]
如题，链接见下，请协助看下，多谢。
https://xoyabc.github.io/2018/05/15/get-file-from-git-server-automatically/

![微信截图_20180517101149.jpg](https://i.loli.net/2018/05/17/5afce4fa9874e.jpg)

**Comment by mzlogin** [comment]
你点击“使用GitHub登录”，然后刷新一下页面应该就好了吧？发布文章之后，需要你自己访问一次页面初始化该页面的评论。

如果还是不行的话，参考一下 <https://github.com/gitalk/gitalk/issues/115> 或者 gitalk 项目里的其它 Issues，或者在 gitalk 项目提问寻求帮助吧~

**Comment by xoyabc** [comment]
@mzlogin 
刚登陆自己账号了，提示“Error: Validation Failed. ”错误。
![1.jpg](https://i.loli.net/2018/05/17/5afceb3ac3c3f.jpg)

**Comment by xoyabc** [comment]
刚看了gitalk的解决方案是修改`layout/_third-party/comments/gitalk.swig`文件，可是没找到这个文件.

**Comment by mzlogin** [comment]
这类问题一般前人们都遇见过了，在 gitalk 的 Issues 里有挺多提问的，见：

<https://github.com/gitalk/gitalk/issues?utf8=%E2%9C%93&q=Error%3A+Validation+Failed.+>

我看了下你这个问题，应该是文章链接过长导致创建标签失败，我数了下你这个文章会创建的标签长度是 51，而标签长度限制为 50，可以参考以下两个链接解决：

* <https://github.com/gitalk/gitalk/issues/124>

* <https://github.com/gitalk/gitalk/issues/102>

**Comment by xoyabc** [comment]
前辈们提供的方法是“id: (location.pathname).split("/").pop().substring(0, 49),”，而咱们的原始为`id: '{{ page.url }}'` ,我修改为`id: '{{ page.url }}.split("/").pop().substring(0, 49)'`直接不显示了。

**Comment by mzlogin** [comment]
我刚刚更新了我的配置，在我的博客里预防了这个问题，你可以参考一下：

https://github.com/mzlogin/mzlogin.github.io/commit/5ef353c011b21c04193df19096bc67a7b7140bec

**Comment by xoyabc** [comment]
感谢大佬~

**Comment by mzlogin** [comment]
不是大佬，不客气的哈~ 😄

**Comment by dejin0916** [comment]
我想问下你们遇到了点击登录调回到主页的情况吗

**Comment by HuangDayu** [comment]
@xoyabc 是博客地址和Authorization callback URL或者Homepage URL不一致的原因。

**Comment by xoyabc** [comment]
> 
> 
> @xoyabc 是博客地址和Authorization callback URL或者Homepage URL不一致的原因。

感谢，已经修复 :smiley:

**Comment by jw-star** [comment]
> 想问下你们遇到了点击登录调回到主页的情况吗

这个问题咋解决，我也遇到了

**Comment by GuardianRain** [comment]
> 你点击“使用GitHub登录”，然后刷新一下页面应该就好了吧？发布文章之后，需要你自己访问一次页面初始化该页面的评论。
> 
> 如果还是不行的话，参考一下 [gitalk/gitalk#115](https://github.com/gitalk/gitalk/issues/115) 或者 gitalk 项目里的其它 Issues，或者在 gitalk 项目提问寻求帮助吧~

点击登录 就一直显示这个 请问您碰到过吗
![image](https://user-images.githubusercontent.com/30609868/109783803-5b394680-7c45-11eb-84b9-005a8185c374.png)

**Comment by mzlogin** [comment]
> > 你点击“使用GitHub登录”，然后刷新一下页面应该就好了吧？发布文章之后，需要你自己访问一次页面初始化该页面的评论。
> > 如果还是不行的话，参考一下 [gitalk/gitalk#115](https://github.com/gitalk/gitalk/issues/115) 或者 gitalk 项目里的其它 Issues，或者在 gitalk 项目提问寻求帮助吧~
> 
> 点击登录 就一直显示这个 请问您碰到过吗
> ![image](https://user-images.githubusercontent.com/30609868/109783803-5b394680-7c45-11eb-84b9-005a8185c374.png)

gitalk 的仓库有很多关于这个问题的讨论 <https://github.com/gitalk/gitalk/issues?q=is%3Aissue+is%3Aclosed> ，维护者已经更新了版本，在讨论里也可以看到其它解决方案。

如果你是使用本模板的最新代码，那其实不用做什么，会自动引用最新版本。如果一再刷新后还是不行的话，那需要刷新一下你本地的缓存，方法：

访问以下 2 个链接：

- <https://purge.jsdelivr.net/npm/gitalk@1/dist/gitalk.min.js>
- <https://cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.min.js?v=1.7.2>

**Comment by LebronAl** [comment]
撤了吧，这个框架配置实在太麻烦了，根本找不到一个完整有效的解决方案，搞了 1 个小时都用不了。弃坑用 [utterances](https://utteranc.es/)，同样是基于 github issue 的，3 分钟配置搞定。
![image](https://user-images.githubusercontent.com/32640567/148485966-6fa983d8-d973-4a3f-8407-93ca074d12db.png)

**Comment by mzlogin** [comment]
> 撤了吧，这个框架配置实在太麻烦了，根本找不到一个完整有效的解决方案，搞了 1 个小时都用不了。弃坑用 [utterances](https://utteranc.es/)，同样是基于 github issue 的，3 分钟配置搞定。 ![image](https://user-images.githubusercontent.com/32640567/148485966-6fa983d8-d973-4a3f-8407-93ca074d12db.png)

嗯 utteranc.es 是不错，这个博客模板里前一阵加入了配置支持。

**Comment by Joker2763** [comment]
![image](https://user-images.githubusercontent.com/104112681/221758383-026b6d51-3573-4ba5-b5a3-bd842037e52c.png)
点击登录之后为啥直接404

**Comment by wayss000** [comment]
> 撤了吧，这个框架配置实在太麻烦了，根本找不到一个完整有效的解决方案，搞了 1 个小时都用不了。弃坑用 [utterances](https://utteranc.es/)，同样是基于 github issue 的，3 分钟配置搞定。 ![image](https://user-images.githubusercontent.com/32640567/148485966-6fa983d8-d973-4a3f-8407-93ca074d12db.png)

感谢大佬分享，我折腾gitalk能有3个多小时，[utterances](https://utteranc.es/) 确实3分钟左右搞定。
