### ISSUE TITLE
建议博主优化一下回到顶部的效果

### ISSUE THREAD

**Issue by xoyabc** [mzlogin/mzlogin.github.io#64]
1.非常感谢博主提供这么优秀的博客主题
2.这几天在使用过程中感觉回到顶部这块还是有可以优化的空间，原因如下：
```
如果文章较长，看到中间部分想回顶部时，目前只能点击底部的top按钮或用鼠标滚动，不是很便利
```
因此，建议博主加一个悬浮的回到顶部按钮，示例见下：
[https://lab.mattvarone.com/projects/jquery/totop/](https://lab.mattvarone.com/projects/jquery/totop/)
![1.jpg](https://i.loli.net/2018/05/22/5b0308c1236ba.jpg)
项目地址：
https://github.com/sksmatt/UItoTop-jQuery-Plugin

**Comment by xoyabc** [comment]
我已经在fork的项目中修改完毕。

步骤如下：

## 1. 分别复制项目[UItoTop-jQuery-Plugin](https://github.com/sksmatt/UItoTop-jQuery-Plugin)中的img、js、css三个目录下的所有文件到assets/images/、assets/js、assets/css

## 2. 修改ui.totop.css文件内容
分别将19及23行中的`../img/ui.totop.png`替换为`/assets/images/ui.totop.png`

## 3. 修改_includes/header.html文件

在第6行`<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />`下增加以下内容：

```
    <!-- back to top start -->
    <link rel="stylesheet" media="screen,projection" href="/assets/css/ui.totop.css" />
    <!-- back to top end -->
```
## 4. 修改_includes/footer.html文件

在倒数第二行`</body>`上方添加以下内容：
```
    <!-- back to top start -->
    <!-- jquery -->
    <script src="/assets/js/jquery-1.7.2.min.js" type="text/javascript"></script>
    <!-- easing plugin ( optional ) -->
    <script src="/assets/js/easing.js" type="text/javascript"></script>
    <!-- UItoTop plugin -->
    <script src="/assets/js/jquery.ui.totop.js" type="text/javascript"></script>
    <!-- Starting the plugin -->
    <script type="text/javascript">
        $(document).ready(function() {
            /*
            var defaults = {
                containerID: 'toTop', // fading element id
                containerHoverID: 'toTopHover', // fading element hover id
                scrollSpeed: 1200,
                easingType: 'linear'
            };
            */
            $().UItoTop({ easingType: 'easeOutQuart' });
        });
    </script>
    <!-- back to top end -->
```

**待github page页面创建后刷新页面即可**

![1.jpg](https://i.loli.net/2018/05/22/5b030c49b648d.jpg)

**Comment by mzlogin** [comment]
可以可以~感谢你的建议与探索，我稍后抽空把这个做进去~

**Comment by xoyabc** [comment]
今天看博文时发现右侧的目录导航没了，撤销第四步`4. 修改_includes/footer.html文件`的操作后恢复了，可能是二者有冲突o(╯□╰)o

**Comment by mzlogin** [comment]
@xoyabc 嗯~估计与引用了两个 jQuery 版本有关

**Comment by xoyabc** [comment]
好的  感谢，我看下。

**Comment by xoyabc** [comment]
刚才我又看了下，将`<script src="/assets/js/jquery-1.7.2.min.js" type="text/javascript"></script>`这行去掉后目录生成那块正常，应该是`<script src="/assets/js/jquery-1.7.2.min.js" type="text/javascript"></script>`与目录生成的js`assets/js/jquery.toc.js`有冲突，不过我不是太懂js，不知道具体问题是什么，我再捣鼓下，不行就借用你的，o(╯□╰)o

**Comment by xoyabc** [comment]
按照你的弄好了，感谢~
PS，我最后又把`.tools-wrapper a`和`.tools-wrapper span.octicon`的样式改成了和[UItoTop-jQuery-Plugin](https://github.com/sksmatt/UItoTop-jQuery-Plugin)里面的ui.totop.css定义的一样了。看习惯了他这个 😄
