### ISSUE TITLE
建议博主把用到的 css 和 js 公共库改为 CDN 链接

### ISSUE THREAD

**Issue by vpday** [mzlogin/mzlogin.github.io#65]
这样修改后，能减轻服务器的压力和加快网站的访问速度。
谢谢！

**Comment by mzlogin** [comment]
这个修改起来也容易，感觉可以留给有需要的人自己去折腾。

**Comment by vpday** [comment]
你没有留下公共库的版本号，所以我不知道去找那个版本。
http://www.bootcdn.cn/
https://www.staticfile.org/

**Comment by whooc** [comment]
希望增加cdn用于加速

**Comment by mzlogin** [comment]
https://hacpai.com/article/1583894928771

今天看到这么一篇帖子，我这几天改造一下加个开关。

**Comment by mzlogin** [comment]
改造了一波，使用 jsdelivr 作为 cdn 了，各位老铁可以帮忙看看加载速度。首次加载估计进首页还是有点慢。

**Comment by whooc** [comment]
> 改造了一波，使用 jsdelivr 作为 cdn 了，各位老铁可以帮忙看看加载速度。首次加载估计进首页还是有点慢。

有效果！

**Comment by mzlogin** [comment]
> > 改造了一波，使用 jsdelivr 作为 cdn 了，各位老铁可以帮忙看看加载速度。首次加载估计进首页还是有点慢。
> 
> 有效果！

好的，谢谢反馈。

**Comment by sunseekers** [comment]
> 改造了一波，使用 jsdelivr 作为 cdn 了，各位老铁可以帮忙看看加载速度。首次加载估计进首页还是有点慢。

我的网页用了这个，但是他cdn挂了，我朋友同样用，没有挂
