### ISSUE TITLE
代码引用中含有大括号变量时生成后前端未显示

### ISSUE THREAD

**Issue by xoyabc** [mzlogin/mzlogin.github.io#68]
1. 引用内容如下：
```shell
name: "{{ new_user_name }}"
```

2.前端显示如下：
![image](https://user-images.githubusercontent.com/7418915/41676387-dbd84d8e-74f7-11e8-90ee-1301e430d10e.png)
只显示出来了`name: ""`，未显示出`name: "{{ new_user_name }}"`

3.github preview显示正常
![image](https://user-images.githubusercontent.com/7418915/41676565-8474ca12-74f8-11e8-89df-f7f09ece398c.png)

猜测可能是生成博客时把`{{ new_user_name }}`当成变量了，而博客中是未设置该变量的，所以生成后显示为空，请帮忙看下是否可以修复此类情况，或者有什么办法可以让前端显示正常呢

**Comment by xoyabc** [comment]
刚搜了下，貌似可以使用raw tag，我试下。
https://stackoverflow.com/questions/3426182/how-to-escape-liquid-template-tags

**Comment by xoyabc** [comment]
name: "{% raw %}{{ new_user_name }}{% endraw %}"
这样些就好了，但是在github上显示不友好
![image](https://user-images.githubusercontent.com/7418915/41678723-76ab5012-74fe-11e8-99c7-ceaa64ba1816.png)

然后又参考：https://github.com/jekyll/jekyll/issues/6217，把github和 Jekyll 的都搞好了 😃

**Comment by mzlogin** [comment]
👍 👍 👍赞
