### ISSUE TITLE
Github 个人仓库问题

### ISSUE THREAD

**Issue by mritd** [mzlogin/mzlogin.github.io#7]
请问博主如何在本地显示 Github 仓库？ 想将博客部署到自己的服务器上，但发现只有在 Github 上才会显示右边的个人仓库，到本地就不显示了

**Comment by mzlogin** [comment]
按我目前的配置在本地也是显示不了的，你可以参考官方的说明 <https://help.github.com/articles/repository-metadata-on-github-pages/> ，有一段是讲“Using repository metadata locally”，我理解应该就是你想要的效果，按它讲的配置一下试试。

我现在火车上，没带电脑自己也试不了，期待你的好消息。

**Comment by mritd** [comment]
好的 谢谢
