### ISSUE TITLE
wiki中的markdown.md中任务列表没给出示例

### ISSUE THREAD

**Issue by QingyiZhang** [mzlogin/mzlogin.github.io#72]
write as follow

```
* 无序列表项 1

* 无序列表项 2

* 无序列表项 3

 - [x] 任务列表 1

 - [ ] 任务列表 2
```

 * 无序列表项 1

 * 无序列表项 2

 * 无序列表项 3

 - [x] 任务列表 1
 - [ ] 任务列表 2

**Comment by mzlogin** [comment]
确实没给，感谢反馈，已经加上了。

以前在博客里还不支持这种写法的，现在也支持上了。
