### ISSUE TITLE
请问模板有没有方法可以自动统计文章的阅读量

### ISSUE THREAD

**Issue by mengalong** [mzlogin/mzlogin.github.io#77]
RT,模板是否支持统计文章的阅读量并在文章详情页、文章列表页显示不同文章的阅读量

**Comment by LfqGithub** [comment]
根据作者的模板，我将这个功能添加了进去，可以参考我的博客：http://yundongxiaoyang.top/

**Comment by mzlogin** [comment]
我今天给模板加上了网站、页面的访问量的统计，有需要的可以参考和更新使用。
