### ISSUE TITLE
评论问题和about 的问题?

### ISSUE THREAD

**Issue by Jhaihao** [mzlogin/mzlogin.github.io#80]
作者你好, ,请问怎么关闭评论的样式页面  和 修改 about 的内容 我把配置都删了 还是显示你的信息 ..

**Comment by mzlogin** [comment]
修改 about 内容：
pages/about.md
_data/skills.yml
_data/social.yml

关闭评论：
_config.yml 文件 comments_provider 改为空

你看看 Jekyll 的官方文档吧，系统了解一下然后自己搜索、尝试，实在找不到答案了再提问。

**Comment by Jhaihao** [comment]
谢谢 我会注意的
