### ISSUE TITLE
作者您好,我想问个关于seo的问题?

### ISSUE THREAD

**Issue by Jhaihao** [mzlogin/mzlogin.github.io#81]
为什么百度搜索马志 可以搜索到你的博客 ,但是我也是按照你的配置去配置的  为什么搜索我自己的博客名 找不到..在百度

**Comment by mzlogin** [comment]
GitHub Pages 屏蔽了百度的爬虫，你搜一下”GitHub Pages 百度收录“这样的关键词，就会发现有很多这样的讨论。我也没有单独为此做什么，为什么百度会收录了这个博客，玄学……
