### ISSUE TITLE
本地jekyll（localhost:4000)可以搜索,但是网页端（chrome)无法搜索，且edge浏览器打开只有文字，没有图片

### ISSUE THREAD

**Issue by LfqGithub** [mzlogin/mzlogin.github.io#85]
网址： yundongxiaoyang.top

**Comment by mzlogin** [comment]
![image](https://user-images.githubusercontent.com/1646590/51798361-ad7c3200-224b-11e9-919b-67c84bec9ec1.png)

JS 报错了。把 _config.yml 文件注释掉的的 146，148 行打开应该就行了。

**Comment by LfqGithub** [comment]
十分感谢您的回复，已经将146-148修改过来，但是仍然无法搜索

**Comment by mzlogin** [comment]
![image](https://user-images.githubusercontent.com/1646590/51809262-21651b80-22da-11e9-8c99-4cf4f93d773f.png)

你可以在浏览器里 F12 看一下，现在在你的博客里搜索仍然报错。

**Comment by LfqGithub** [comment]
多谢楼主的提醒，使用F12找到网页中错误，并且搜索了报错信息，发现了解决方案：https://github.com/mmistakes/so-simple-theme/issues/228， 解决方法为： 将_config.yml中
url: http://lfqgithub.github.io/
改为：
url: http://yundongxiaoyang.top
即可。
太感谢楼主了！
