### ISSUE TITLE
文章中如何显示文件中的代码？

### ISSUE THREAD

**Issue by LfqGithub** [mzlogin/mzlogin.github.io#86]
如我有一个博客： a.md, 想要添加 b.py 中的代码，是否可以直接include b.py，而不是将b.py中的代码复制到a.md中（这样下次改进b.py就不用同步修改文章了），谢谢博主！

**Comment by mzlogin** [comment]
GitHub 仓库里的代码文件我不知道用什么办法，但 gist 里的文件可以引入进来显示，不过……gist 在国内一直是被墙的状态。

**Comment by LfqGithub** [comment]
嗯嗯，谢楼主。之前试过，貌似{include path/b.py}可以，但是不知怎得，后面就报错了。好诡异
