### ISSUE TITLE
关于评论配置的问题? 按照作者的配置去 还是失败了

### ISSUE THREAD

**Issue by Jhaihao** [mzlogin/mzlogin.github.io#88]
作者你好, 又来麻烦你  关于评论的问题 我谷歌了几天了 还是解决不了 我怀疑我的智商或者搜索的方式 有问题 ,现在求助于你 能否帮忙看看 我的配置文件呢 , ,谢谢你了 ,,

**Comment by mzlogin** [comment]
看着没啥问题啊，你在自己的页面用 GitHub 登录评论框然后刷新看看？

**Comment by Jhaihao** [comment]
昨天 翻了 你的issues 的问题   找到了 方法了 , ,原来一直都没有登录  我登录后 刷新一次后就可以了 谢谢你了

**Comment by mzlogin** [comment]
OK 解决了就好。

**Comment by PeterXiaosa** [comment]
看了大家提的issue，也去gittalk下面看了issue。但是还是没有找到答案，想请教一下。我配置了配置文件之后集成了gittalk，但是打开的时候评论出会显示Error: Not Found. 百度了下有人说是配置文件配置错了，但是我检查了好几遍，配置都是对的呀，所以想来着请教一下。

**Comment by mzlogin** [comment]
@PeterXiaosa 新建一个名叫 `blog-comments` 的项目，或者将 _config.yml 文件第 106 行改成 `PeterXiaosa.github.io`

**Comment by PeterXiaosa** [comment]
谢谢大哥~ 网上说这个用自己仓库的名 但是我之前修改过为我自己的仓库名没有作用 然后又改回去了 可能那个时候我其他的某个参数可能不对吧 刚刚修改了下 一下就见效了 是在太感谢大哥了~~~
