### ISSUE TITLE
亲爱的楼主，请问如何添加https啊，谷歌浏览器现在对http很不友好了啊，我想加入这个功能。

### ISSUE THREAD

**Issue by LfqGithub** [mzlogin/mzlogin.github.io#90]

**Comment by mzlogin** [comment]
项目的 Settings 里有一项 Enforce https，勾选，然后将 _config.yml 里的 url 改成 https 的。

可以参考 https://help.github.com/en/articles/securing-your-github-pages-site-with-https

**Comment by LfqGithub** [comment]
谢谢楼主，记得以前github pages 不支持自定义域名的，现在竟然支持了，太开心了！
