### ISSUE TITLE
HTTPS配置后导致样式显示失败问题

### ISSUE THREAD

**Issue by GrayXu** [mzlogin/mzlogin.github.io#91]
在http的情况下访问一切正常，在设置中开启了https后，界面的样式（包括小图标等）加载失败，变成白底黑字，但markdown排版正常（包括文章内图片），gitalk加载正常，使用性功能正常。

grayxu.cn

**Comment by GrayXu** [comment]
发现原因了，浏览器认为这个HTTPS不可信，就不加载样式相关js了…

**Comment by oceanlvr** [comment]
@GrayXu 同样的，在开启了 https 后无法你正常显示样式biao。 请问您是如何解决这个问题的？
[https://adameta.top/]https://adameta.top/
😢

**Comment by oceanlvr** [comment]
已经解决，感谢。
