### ISSUE TITLE
无法使用Google Analytics 

### ISSUE THREAD

**Issue by tic-toc-developer** [mzlogin/mzlogin.github.io#97]
修改_```config.yaml``` 中的```google_analytics: ```一项后, 无法被Google统计, 请问还有需要修改的地方吗?

**Comment by tic-toc-developer** [comment]
测试了一下, 应该是```footer.html```中的```{% if site.google.analytics_id %}```条件未满足, 项目地址<https://github.com/tic-toc-developer/tic-toc-developer.github.io>, 恳请解惑

**Comment by tic-toc-developer** [comment]
已发现问题 我把```_config.yaml```中的```Analytics```内容改错了 修正后可以正常使用了

**Comment by banklc** [comment]
博主，这个googlex analysis新版的只要id-G开头的，也是只要_config.yaml中的Analytics-id替换了就可以吗？但是我替换了感觉没被统计到
