### ISSUE TITLE
search好像不支持全文搜索功能，只能搜标题，如果我需要新增该功能，有哪些实现思路呢？

### ISSUE THREAD

**Issue by HwiLu** [mzlogin/mzlogin.github.io#98]

**Comment by mzlogin** [comment]
目前是不支持，因为搜索的数据源里没有添加全文内容。
如果需要支持全文搜索，那可以在搜索的数据源里添加全文内容，即在 assets/search_data.json 文件里进行配置。

但不太建议这么做，这样会导致该 json 文件非常大，拖慢页面的加载速度。

你可以进行尝试，然后看这样的性能可不可以接受，可接受也行，不可接受的话再搜搜其它方案试试，有找到好的方案也希望你能反馈给我。 :-)

**Comment by HwiLu** [comment]
> 你能反馈给我。 :-)

好的，谢谢大佬

**Comment by HwiLu** [comment]
好的，谢谢大佬。
