### ISSUE TITLE
文章description无法使用带空格的英文句子

### ISSUE THREAD

**Issue by HwiLu** [mzlogin/mzlogin.github.io#99]
比如，如果description为`Caused by: java.io.IOException: Mismatch in length of `，该篇文章在所有页面都会显示异常。

**Comment by mzlogin** [comment]
可以使用英文双引号把句子括起来。

see <https://stackoverflow.com/questions/11301650/how-to-escape-indicator-characters-i-e-or-in-yaml>

**Comment by HwiLu** [comment]
是的，我也发现了，后面想了一下，应该是冒号引起的而不是空格。

**Comment by mzlogin** [comment]
是的，应该是冒号，估计是 YAML 的语法限制。
